### ISSUE TITLE
Feature flags user blast radius changes incorrectly when deleting conditions

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#18743] opened 2023-11-20 10:49 UTC
## Bug description

If you remove a condition, the condition below will take its place which is fine, but it shows the "this affect x% of people" from the condition you just deleted

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Raised by a user https://posthoghelp.zendesk.com/agent/tickets/7375

**Comment by havenbarnes** [comment] 2024-11-11 23:48
I attempted reproducing this issue but have been unable to. It appears that we are rendering the correct blast radiuses for the correct condition set even after adding / removing sets. Closing as can't reproduce for now, my guess is this was resolved in the last year!

**Closed by havenbarnes** 2024-11-11 23:48 UTC
Labels: bug, feature/feature-flags, team/feature-flags
