### ISSUE TITLE
When you visit a specific graph link but have to sign in, the link is lost

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3415] opened 2021-02-21 08:41 UTC
## Bug description

* Get sent link by someone
* If *not* logged in to PostHog
* Login
* I am taken to the generic insights page, not the link for the relevant graph

## Expected behavior

* Get taken to the appropriate URL after logging in

**Comment by ungps** [comment] 2021-03-03 21:46
Hello,

I couldn't reproduce this. I tried a couple of different scenarios but all of them seems to be working just fine (after I logged in, I was redirected to the right page). Maybe this got fixed in the meantime? If it was not, could you please give more details? I would like to fix this.

**Comment by Twixes** [comment] 2021-03-04 16:35
Thanks for the interest @ungps! This issue is now fixed with PostHog/posthog-cloud#89, it was PostHog Cloud-specific.

**Closed by Twixes** 2021-03-04 16:35 UTC
Labels: UI/UX, bug, priority 3
