### ISSUE TITLE
Feature flags load time

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1645] opened 2020-09-11 01:12 UTC
## Bug description

We have a user reporting that their implementation is receiving this error continuously when loading feature flags.
```
"isFeatureEnabled for key \"show_blue_button\" failed. Feature flags didn't load in time."
```

## Expected behavior
Feature flags should load.

## Environment
- PostHog cloud. Frontend integration using PostHog JS library.

**Comment by razor-x** [comment] 2020-09-12 19:31
This is my init script. I added an extra `ph.reloadFeatureFlags()` after the initial feature flag event triggers. This seems to help.

```ts
const timeout = 5000
const featureFlagInterval = 60 * 1000

const init = async () => {
  let isResolved = false

  return new Promise((resolve) => {
    const handleError = (err: Error) => {
      log.error(err)
    }

    setTimeout(() => {
      if (isResolved) return
      const err = new Error(`PostHog timeout after ${timeout}`)
      handleError(err)
      isResolved = true
      resolve()
    }, timeout)

    posthog.init(apiKey, {
      debug,
      loaded: () => {
        try {
          posthog.register({ app, env, version })
          setInterval(() => {
            const ph = posthog as any
            ph.reloadFeatureFlags()
          }, featureFlagInterval)
          posthog.onFeatureFlags(() => {
            // UPSTREAM: Force additional reload
            const ph = posthog as any
            if (!isResolved) ph.reloadFeatureFlags()
            isResolved = true
            resolve()
          })
        } catch (err) {
          handleError(err)
          isResolved = true
          resolve()
        }
      }
    })
  })
}
```

**Comment by mariusandra** [comment] 2020-09-16 06:29
@paolodamico 
- "Using PostHog JS Library" == npm? Latest version?
- When is the `isFeatureEnabled("show_blue_button")` called? We probably need to make a request to the server in order to get the data for the flags. It's possible that's not done? In that case the `onFeatureFlags` callback should be used.
- How is the `show_blue_button` feature calculated? Is it a simple feature flag with just a rollout percentage or something more complicated that requires a db query to get the results?

**Comment by paolodamico** [comment] 2020-09-16 12:41
@razor-x can you confirm points 1 & 3 from @mariusandra ? For point 2 I believe the snippet shows the `onFeatureFlags` callback in use. Maybe @razor-x if you could check the network logs on your app to see if the request is being sent to the server and if there's any response or timeout from the server?

**Comment by razor-x** [comment] 2020-10-21 19:00
Sorry for no updates in a while. Flags have been working better for me since adding the extra reload.

```
         posthog.onFeatureFlags(() => {
            // UPSTREAM: Force additional reload
            const ph = posthog as any
            if (!isResolved) ph.reloadFeatureFlags()
            isResolved = true
            resolve()
          })

```

I am already using a one minute polling interval for updates, so the extra call is not much overhead for the safety it provides. I agree though it should not be needed, so I may try removing it to see if any of your recent updates have fixed the bug.

**Comment by Twixes** [comment] 2021-01-25 11:54
Hey @razor-x, I think we can close this, but if you have any feedback or persisting issue with PostHog, we'd love to hear from you!

**Closed by Twixes** 2021-01-25 11:54 UTC
Labels: bug

**Comment by iwasrobbed** [comment] 2023-08-03 16:38
Either the docs are wrong or there's a race condition in the Posthog code. Even calling `reloadFeatureFlags` does not prevent the warning.

```javascript
// Ensure flags are loaded before usage.
// You'll only need to call this on the code for when the first time a user visits.
posthog.onFeatureFlags(function() {
    // feature flags should be available at this point
    if (posthog.isFeatureEnabled('my-feature') ) {
        // do something
    }
})

// Otherwise, you can just do:
if (posthog.isFeatureEnabled('my-feature') ) {
    // do something
}
```

Even checking within the `onFeatureFlags` callback still throws a warning:

>isFeatureEnabled for key "my-feature" failed. Feature flags didn't load in time. 

I see a cookie stored:
```
{
   "distinct_id":"010420bb-7b77-47fa-bdf6-9d748ca59781",
   "$device_id":"188df9829051ba6-04aeddb1fb41b5-1b525634-29b188-188df9829062d72",
   "$user_state":"identified",
   "$sesid":[ // stuff here],
   "$session_recording_enabled_server_side":true,
   "$autocapture_disabled_server_side":false,
   "$active_feature_flags":[
      
   ],
   "$enabled_feature_flags":{
      
   },
   "$feature_flag_payloads":{
      
   },
   "$console_log_recording_enabled_server_side":true,
   "$session_recording_recorder_version_server_side":"v2",
   "$user_id":"010420bb-7b77-47fa-bdf6-9d748ca59781",
   "$stored_person_properties":{
      "email":"rob@mydomain.com",
      "name":"rob phillips"
   }
}
```

There is one fully-rolled out feature flag enabled on the Posthog admin dashboard as well, notably missing from the above cookie.

Very unclear what the expected behavior here is meant to be.

**Comment by neilkakkar** [comment] 2023-08-03 16:52
What version are you on @iwasrobbed ?

**Comment by neilkakkar** [comment] 2023-08-03 16:53
and, how are you initialising posthog?

**Comment by iwasrobbed** [comment] 2023-08-03 17:10
@neilkakkar Abort, user error. I was creating the flag on the wrong env/project.

Seems like this error only shows if you're testing a flag that either hasn't been bootstrapped in the Posthog config or doesn't exist in the project after loading.

**Comment by neilkakkar** [comment] 2023-08-03 17:28
It shows up if _no_ flags exist after bootstrapping/loading, and you're trying to call `getFeatureFlag()`. If other flags existed in this case, it wouldn't have shown up 👀
