### ISSUE TITLE
Breakdown by multiple metrics

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#933] opened 2020-06-06 16:55 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Multiple breakdown options in the Trends page

**Describe alternatives you've considered**

**Additional context**
When creating a trend graph it is currently only possible to break down by one metric. Breaking down by a combination of metrics such as "Browser" + "Browser Version" would be a very handy tool.

***Thank*** you for your feature request - we love each and every one!

**Comment by paolodamico** [comment] 2021-05-20 14:40
Duplicate of #938

**Closed by paolodamico** 2021-05-20 14:40 UTC
Labels: enhancement
