### ISSUE TITLE
Sprint - Apr 15 to Apr 26, 2024

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#21456] opened 2024-04-10 08:22 UTC
# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by pauldambra** [comment] 2024-04-10 08:24
# Team Replay-apotamus

OMG first sprint of the quarter!

**Support hero:** David

- Paul - out for one week (although dipping back in for super days)
- Bank Holiday monday


## Retro

- longer retro tomorrow

## items from previous sprint

### High priority

✅ iOS session recording 
    - alpha is ready for release
✅ 5 _more_ Open Source Android apps tested with android replay 
    - big list of nits and opportuntities here https://docs.google.com/document/d/1gzY3FybfRr84eE7W_QNlCNL21ueAg7W7Evth6AAYNHs/edit
✅ test error clustering with PostHog and ideally with some customers
   - this is out for PostHog 
   - really need to validate this - so we ignore productionising it a little longer 🙈 

### Low priority / side quests

🟡 remove user agent parsing from posthog-js @pauldambra 
   - everything is setup for the plugin improvments but not prioritised due to other work
🔴 stop running replay clients when over quota @pauldambra 
  - not prioritised due to other work
🔴 [css-in-js lots](https://github.com/PostHog/posthog/issues/18520) of support requests here @daibhin 
  - not prioritised due to other work

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red

- quality and consolidation
    - mobile replay open beta
    - replay captures every site
    - people can find the valuable recordings 
- Error tracking MVP
- Hire 2 amazing colleagues
   - 10 interviews this week 🫠
   
### High priority

 - Paul is going to sicily to build heatmaps 3000 with Ben
     - https://github.com/PostHog/posthog/issues/21099
 -  we've got a backlog of nits and improvements to Android replay getting ready for advertised open beta
 - we've got a heavy support backlog
 - so we're starting the quarter with a :fix all the things: sprint

### Low priority / side quests

**Comment by Twixes** [comment] 2024-04-10 09:06
# Team Pro(fessional)duct Analytics

**Support hero:** @mariusandra 

## Retro

- Thomas: ~~Support &~~ Rolling out HogQL-based insights & HogQL support ✅
- Michael: ~~Project environments & support rollover~~ Support ✅
- Julian: Legacy logic/filter cleanup, improve dashboard logic & reloads. ➡️ Async querying here
- Tom: HogQL & Data Warehouse. Type system? ✅

## Hang over items from previous sprint

- Roll out HogQL-based Paths (time scale depends on whether we find compatibility issue)
- Reworking `dashboardLogic`

## OKR

## OKRs Q2 2024

- HogQL-based querying
  - Convert the remaining legacy queries to HogQL and release to public (Thomas, Julian, Marius)
    - 🟢 Insights – will be done this sprint with the rollout of Paths
    - ⚪ Cohorts 👈 some time later
  - Remove legacy querying backend (Thomas, Julian)
    - 🟠 Clean up or rewrite dashboardLogic 👈 this sprint
    - ⚪ Convert filters to query (insights, notebooks, activity log, experiments)
  - Missing Product Analytics features (Thomas, Julian)
    - ⚪ Breakdowns (multiple) in literally everything
    - ⚪ Make a list based on GitHub issues from customer requests…
  - Missing HogQL features (Tom, Marius)
    - 🟠 Type system, JSON 👈 Data Warehouse is on this
    - ⚪ Missing things when building funnels

- Querying and processing performance (Thomas, Julian)
  - Global performance overview dashboards
    - ⚪ Insights
    - ⚪ Exports
    - ⚪ Cohort recalculations
  - Query request tracing
    - ⚪ Possibly query runner Python optimizations
    - ⚪ Exports improvements
  - ⚪ Identify top 5 query optimizations in terms of impact

- Artificial Hog / Post Intelligence (Michael)
  - ⚪ Ask a question to get a magical insight (aware of your taxonomy)
  - ⚪ Figure out infra for upgrading queries and models
  - ⚪ Product-wide framework for opting into sharing with OpenAI

- Activation (side quest: Michael)
  - ⚪ Michael to work with Growth to identify optimizations to getting started with Product Analytics

### High priority

- Marius: Support
- Michael: Project environments
- Julian: Dashboard logic rework
- Tom: Effectively Data Warehouse

### Low priority / side quests

- Start converting `filters` to `query`, probably for Julian

**Comment by danielxnj** [comment] 2024-04-10 13:17
# Team Infra

**Support hero:** @danielxnj 

## Hang over items from previous sprint

1. 🟢  Spontaneous look into AZ aware routing to try and reduce our biggest cost centre
- We are stuck because Aurora only provides one AZ endpoint for the writer instance so we can not remove the cross AZ traffic.
1. 🔴 Purchase reserved RDS instances @frankh 
- why? Risk vs cost works out - to be fully confirmed with pipeline team
4. 🟡 Get app onto Canary deploys now that we are on contour @danielxnj 
- app.dev is on argo rollouts (not actually canarying but deploying correctly)
5. 🔴 Test out capture-rs traffic with contour @frankh 
- Had enough ingress issues the last week or so that we took a pause here
7. 🟡 Get flagged PoC for proper permissions out @benjackwhite 
- So close - just tests to finalise to get merged.
8. 🟢 Add OOM and restart alerting for all deployments @danielxnj 

## OKR

1. 💪 Deploy with confidence 🟡
- Finalize our Canary Deploy process 🟡
- Support rust capture to full release using traffic shaping
2. 🚨 Improved alerting and monitoring
3. 🔒 Deeper Security
4. 💰 Continued cost control
5. 🖖 Splitting up the monolith

### High priority

1.  Secret management tooling
- why? All secrets are leaked in the pods @danielxnj 
2. Interviews. @benjackwhite 
3. Canary roll out to every deployment @frankh 
4. Work with Xavier and the pipeline team on traffic mirroring using contour @frankh 


### Low priority / side quests
- Improve Kafka alerting

**Comment by robbie-c** [comment] 2024-04-10 13:46
# Team Web Analytics

**Support hero:** n/a

## Retro
High priority
- [x] personless events posthog-js changes
- [ ] personless events UI problem solving whack-a-mole
    - ongoing
- [x] Write more docs for web analytics (e.g. what is a Channel Type?) and add more tooltips to web analytics

Low priority
- [ ] Session filters for all posthog events
  - WIP
- [ ] Add session properties to the property definition endpoint
  - WIP

## Hang over items from previous sprint
- personless events UI problem solving whack-a-mole
- Session filters for all posthog events
- Add session properties to the property definition endpoint

## OKR

⚪ Make querying fast enough for large customers
⚪ Do personless events work where necessary (unknown amount of work)
⚪ Iterate on customer feedback
⚪ Product management work

### High priority
- personless events UI problem solving whack-a-mole

### Low priority / side quests
- Session filters for all posthog events
- Add session properties to the property definition endpoint

**Comment by raquelmsmith** [comment] 2024-04-10 14:35
# Team Growth


## Retro
<details>
<summary>Retro items</summary>
- [x] Team offsite!


### High priority
- @raquelmsmith 
    - [x] Support billing for person processing addon - this took up all of my time
    - [x] Support addon features for paygate mini
    - [x] [feat: point people to contact sales for enterprise from pricing page](https://github.com/PostHog/posthog.com/pull/8164)
    - [ ] Dashboard creation from onboarding
    - [ ] Feature gating for activity panel
      - Migrate customers
    - [ ] Feature gating for automatic provisioning
      - Migrate customers
- @xrdt 
        - [ ] Session replay pricing change plan: in progress, see below for details
- @zlwaterfield 
    - [x] RFC for simpler upgrading - comments done, starting work on it
    - [x] Move the Growth 2.0 dashboard to a Notebook and finish it the charts we have data for - https://us.posthog.com/project/2/notebooks/mw9VwBA0 
    - [ ] Helping Ian improve Next.js documentation - found proxy error and created issue with next https://github.com/vercel/next.js/issues/63948, no documentation changes yet
    - [x] Continue email verification investigation - rates here have lowered, shipped verification support modal
    - [ ] Review / test Michael’s dark mode PR: https://github.com/PostHog/posthog/pull/21149 - no movement here
    - [x] Looking at some recurring Sentry bugs (e.g https://github.com/PostHog/billing/pull/499) - logs of bugs fixed and number of errors it much lower
</details>




## OKR
✅=finished  🟡=in progress 🔴=won't finish ⚪=haven't started
1. ⚪ Create a flow in product analytics onboarding to fill out a dashboard template using actions (Raquel)
2. 🟡 Simplify our subscription flows (Zach, supported by Raquel)
3. Launch pricing changes (Bianca, Raquel)
    - 🟡 Personless events - will help us reach more customers at an affordable price
    - Data warehouse - it's becoming pretty useful, we should charge for it
    - Session replay - we can reduce costs to improve retention and reach more people


## This sprint
- @raquelmsmith 
    - [ ] Support billing for person processing addon - get it to a launch-able spot this week. See https://github.com/PostHog/billing/issues/504 for status and tasks
    - [ ] Feature gating for activity panel
      - Migrate customers
    - [ ] Feature gating for automatic provisioning
      - Migrate customers
- @xrdt 
    - [ ] Session replay pricing change plan:
      - [ ] Legacy paid customers all get controls
      - [ ] New prices PR up
      - [ ] Working with Annika to nail down migration strategy
      - [ ] Continuing to look into snags I ran into last time with compare_prices script
    - [ ] Invoice syncing and revenue issues
      - [ ] Revenue drop over weekend
      - [ ] We seem to lose invoices when billing cycles roll over
      - [ ] Sentry error about type → id 
    - [ ] Move customer <> (stripe_customer_id, stripe_sub_id) to a One to Many relationship, [pr in progress](https://github.com/PostHog/billing/pull/516)
- @zlwaterfield 
    - [ ] Billing changes - auto-subscribing users to all products (starting with new users)
    - [ ] Plan the pricing/plan/product structural changes - how do we convey plans vs products?
    - [ ] Spend time improving annual/credit Stripe webhooks - these are almost all of the Sentry errors left
    - [ ] Update Slack message for growth dashboard
    - [ ] Follow up on Next.js proxy issue with Vercel and update Next.js documentation for a note on the reverse proxy bug
    - Metrics to watch:
      - How many organizations sign up without a name: https://us.posthog.com/project/2/insights/SmImt4r7  (see if this is an indicator of lower chance to subscribe to paid plan)
      - Sign up benefits - generic, vs product analytics focused vs logs: https://us.posthog.com/project/2/experiments/24738  
      - Email verification support tickets https://us.posthog.com/project/2/experiments/26053

**Closed** 2024-04-29 16:12 UTC
Labels: sprint
