### ISSUE TITLE
The `view source` -> `Update and run` button seems to be broken

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#17839] opened 2023-10-06 09:05 UTC
## Bug description

![2023-10-06 at 11 04 38@2x](https://github.com/PostHog/posthog/assets/13001502/9c7a2005-b7f2-45e2-94ea-675812f1bf90)

## How to reproduce

1. Open a trends insight
2. Click three dots icon
3. Click view source
4. Try edit the source and click update
5. Nothing happening

## Workaround

Visit https://app.posthog.com/debug and paste the source there.

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/6047

related bug report: https://github.com/PostHog/posthog/issues/17839

**Comment by Justicea83** [comment] 2023-10-10 12:51
@MarconLP I know you've been assigned this, if you're busy, it can be my first pick 😄

**Comment by mariusandra** [comment] 2023-10-10 14:06
@Justicea83 we don't ask for permission to work on things, nor assign issues (yes I see what happened here). The first correct PR wins.

**Comment by Justicea83** [comment] 2023-10-11 00:45
After digging for hours, I realized this regression was caused by this [PR](https://github.com/PostHog/posthog/pull/17522).
@thmsobrmlr I'm sure you didn't test this out after your changes.

**Comment by MarconLP** [comment] 2024-02-16 09:30
+1 https://posthoghelp.zendesk.com/agent/tickets/10592 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/13220)

**Comment by MarconLP** [comment] 2024-03-18 07:22
+1 https://posthoghelp.zendesk.com/agent/tickets/11762 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/13997)

**Closed** 2024-06-25 09:32 UTC
Labels: bug, team/product-analytics
