### ISSUE TITLE
Add a dashboard-wide filter or time period

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#937] opened 2020-06-06 19:13 UTC
**Is your feature request related to a problem? Please describe.**
While looking at an application overview on a dashboard with several graphs I cannot switch from looking at todays stats or the last 1 week or the last 1 month to see how my overview is changing throughout each timeframe.

There are also cases where I would like to filter down to a custom property to see how my dashboard looks for that one item.

**Describe the solution you'd like**
Having a row at the top of the dashboard that contains the time interval options and filtering, which when changed then *temporarily* applies those to all graphs within the dashboard.

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment] 2020-06-08 11:46
Duplicate of #780

**Closed by timgl** 2020-06-08 11:46 UTC
Labels: enhancement
