### ISSUE TITLE
Funnel query returns suspect results

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#3728] opened 2021-03-23 10:53 UTC
## Bug description

I'm trying to analyze conversion for funnels project using the following query:

![image](https://user-images.githubusercontent.com/148820/112135483-807efc00-8bd6-11eb-9d7d-99d3d2920e02.png)

However two things don't line up:
1. I see test users included in the output
2. The number of people who have finished the 2nd step does not match the people table, which shows fewer people

## Expected behavior

1. Test users excluded
2. Number of people matches

## How to reproduce

1. Run the above funnels query
2. Check results
3. See disparencies

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by timgl** [comment] 2021-03-23 11:18
I'd suggest this is a duplicate of #3668

**Comment by EDsCODE** [comment] 2021-03-23 19:11
Number doesn't match even without trying to filter test accounts. It could also be something where there's event data related to a number of users but somehow we weren't able to retrieve all of the person data for the table

**Comment by kpthatsme** [comment] 2021-03-24 20:55
another data point re: person counts, I was looking at a steps chart earlier and I saw a user repeated twice within a funnel step when clicking into it

**Comment by macobo** [comment] 2021-03-25 08:48
Weird - this query and others related seem to work for me now, both issues having disappeared.

**Comment by EDsCODE** [comment] 2021-03-30 15:45
Large amount of this was resolved after @fuziontech redid the person_distinct_id table. Will close for now but monitor and reopen if necessary

**Closed by EDsCODE** 2021-03-30 15:45 UTC
Labels: analytics-filters, bug, funnels
