### ISSUE TITLE
formula mode broken for some formulas

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#13388] opened 2022-12-18 19:31 UTC
## Bug description

Formula does not work for the following query

A:  Pageview total count filtered by session duration > 30 sec
B: Pageview total count

Formula: A/B

![image](https://user-images.githubusercontent.com/56287180/208315675-14fea444-969c-4acc-9b0b-14827a56777e.png)

![image](https://user-images.githubusercontent.com/56287180/208315682-565ad783-eaa9-43ff-8605-58c58d291425.png)

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. 
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by camerondeleone** [comment] 2022-12-18 19:35
This may be a larger issue where the session duration logic breaks formula mode, but given that we can render both series properly I'm hoping it's an easy fix?

**Comment by camerondeleone** [comment] 2022-12-19 15:14
@neilkakkar for visibility

**Comment by thmsobrmlr** [comment] 2023-04-19 11:48
Closing as duplicate of https://github.com/PostHog/posthog/issues/15090

**Closed by thmsobrmlr** 2023-04-19 11:48 UTC
Labels: bug
