### ISSUE TITLE
Support for Cloudflare Workers 

### ISSUE THREAD

**Issue by abhagsain** [PostHog/posthog#13484] opened 2022-12-26 08:20 UTC
I tried using `posthog` with [Cloudflare Workers](https://developers.cloudflare.com/workers/) and it gave this error.

```js
✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "createHash"

    ../node_modules/posthog-node/lib/index.esm.js:1:9:
      1 │ import { createHash } from 'crypto';
        ╵          ~~~~~~~~~~


✘ [ERROR] Build failed with 1 error:

  ../node_modules/posthog-node/lib/index.esm.js:1:9: ERROR: No matching export in
  "node-modules-polyfills:crypto" for import "createHash"


```

This is because the `crypto` library that `posthog` uses is from `node` and Cloudflare worker uses Web Crypto APIs ([Worker Docs](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/))

For my use case, I'm okay with sending the events with HTTP requests but would love to get support for Cloudflare workers as well.

**Comment by xvello** [comment] 2023-01-18 08:48
This error is caused by [the feature-flag evaluation logic using crypto.createHash('sha1')](https://github.com/PostHog/posthog-js-lite/blame/2f8efcc00ad843d4554382dc821fb28469c4533e/posthog-node/src/feature-flags.ts#L376), that is not available on CF Workers. Their documentation [states the incompatibility and their alternative API](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/), so we'd need to switch between the two APIs based on availability.

A contribution from someone experienced with the CF API would be welcome!

**Comment by VladymyrPylypchatin** [comment] 2023-03-22 12:48
@abhagsain I faced the same issue with Cloudflare Workers.

Hacked together a workaround in this fork https://github.com/VladymyrPylypchatin/posthog-js-lite

Basically replaced crypto with the CryptoJs

**Comment by nizarmah** [comment] 2023-06-09 20:37
I believe this has already been addressed by https://github.com/PostHog/posthog-js-lite/pull/94

Looking at other usages of `crypto.createHash` across the different available repos, I don't think there's anything else that might be running on a worker.

<details>
<summary>I might be wrong though, so I've listed them all below.</summary>

* **PostHog/snowflake-connector-nodejs**:
  * [1](https://github.com/PostHog/snowflake-connector-nodejs/blob/d375e1e6688caea570d1c045629aa01b324beed0/test/integration/testStreamRows.js#L361)
  * [2](https://github.com/PostHog/snowflake-connector-nodejs/blob/d375e1e6688caea570d1c045629aa01b324beed0/lib/file_transfer_agent/file_util.js#L135)
  * [3](https://github.com/PostHog/snowflake-connector-nodejs/blob/d375e1e6688caea570d1c045629aa01b324beed0/lib/agent/cert_util.js#L89)
  * [4](https://github.com/PostHog/snowflake-connector-nodejs/blob/d375e1e6688caea570d1c045629aa01b324beed0/lib/authentication/auth_keypair.js#L139)
* **PostHog/app-dev-server**:
  * [1](https://github.com/PostHog/app-dev-server/blob/b30b2141f86828ad107da3c133a7e4a20220f2f0/src/server.mjs#L81)
  * [2](https://github.com/PostHog/app-dev-server/blob/b30b2141f86828ad107da3c133a7e4a20220f2f0/src/server.mjs#L81)
* **PostHog/apps**:
  * [1](https://github.com/PostHog/apps/blob/0ed16c0beaba874af50d2410bad20d22a345b042/packages/posthog-app-unduplicates/index.ts#L65)
  * [2](https://github.com/PostHog/apps/blob/0ed16c0beaba874af50d2410bad20d22a345b042/packages/posthog-app-unduplicates/index.test.ts#L4)
* **PostHog/downsampling-plugin**:
  * [1](https://github.com/PostHog/downsampling-plugin/blob/31debcfbf6577e990e23e2ff9ebe600ae0fbf2bf/src/index.ts#L27)
* **PostHog/posthog-migrate-meta**:
  * [1](https://github.com/PostHog/posthog-migrate-meta/blob/c10519b979fbf2a2f895d4de217e3bbd61c84bc5/utils.ts#L34)
* **PostHog/plugin-server**
  * [1](https://github.com/PostHog/plugin-server/blob/beb21a048e56e24175be97cb7ca6c2ce0b738858/src/utils/db/utils.ts#L104)
</details>

---

~~For future reference, WebCrypto's [`crypto.subtle.digest`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#basic_example) is an alternative option for [`rusha`](https://github.com/srijs/rusha) in case it becomes deprecated or anything.~~ Actually, it's an async method, not sure about that.

**Comment by neilkakkar** [comment] 2023-06-10 08:31
Think we're good here, thanks!

**Closed by neilkakkar** 2023-06-10 08:31 UTC
Labels: enhancement, good first issue, libraries
