### ISSUE TITLE
Feature: Filters, search and typos for orgs, instances, projects

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10988] opened 2022-07-26 16:42 UTC
## Is your feature request related to a problem?

Persons view:

<img width="449" alt="Screenshot 2022-07-26 at 17 41 39" src="https://user-images.githubusercontent.com/84011561/181062810-13ad608c-620a-4015-84f7-b3d09dcf6bb8.png">

Versus Orgs view:
<img width="449" alt="Screenshot 2022-07-26 at 17 41 55" src="https://user-images.githubusercontent.com/84011561/181062860-2b99a99c-b1c8-4a6a-b09d-49d7f5e228ee.png">

## Describe the solution you'd like

Would seem beneficial if it was possible to search or filter organizations. This is also missing for Instances and Projects. 

Also, `Organizations`, `Instances` and `Projects` shouldn't be pluralised in the table headers. It should be singular, as it is for `Person`.

**Comment by clarkus** [comment] 2022-07-26 18:33
I think the problem is broader than just the persons feature. Generally we need a reusable data table filtering component that can adapt to the various scenarios in which we use data tables. Adding a keyword search is part of that, but there are typically some more valuable attributes that we can promote as high priority filters. There might also be other attribute filters that are useful, but shouldn't be place prominently. 

This recently came up during the session recording improvements work. Generally we need a way make important filters available prominently with some overflow container for more complex / less valuable filters. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=11953:60276#228515249

**Comment by joethreepwood** [comment] 2022-07-27 08:31
I should have known it would be more complex than I thought 🤦

**Comment by neilkakkar** [comment] 2022-07-27 10:23
> I should have known it would be more complex than I thought 🤦

Don't let that discourage you from opening new issues, Joe! :) In some cases, it _might_ just be a problem we've overlooked. 

This specific case is more than just a UX problem though, since the backend functionality to search groups doesn't exist yet. I'll close this as duplicate of https://github.com/PostHog/posthog/issues/7265

**Closed by neilkakkar** 2022-07-27 10:23 UTC
Labels: enhancement, feature/persons, feature/group-analytics, components

**Comment by clarkus** [comment] 2022-07-27 15:52
I'll file an issue for a core filtering component that compliments data tables. I will cross link this and other relevant issues and ping you for a review @joethreepwood.
