### ISSUE TITLE
Session recording feature flag leaking?

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1844] opened 2020-10-13 08:25 UTC
## Bug description

We have a beta feature up on app.posthog.com called "session recording" (via rrweb). Search and you'll see the various PRs for it.

I'm logged in as marius.andra+kea@gmail.com and even though I'm not in the "posthog team" cohort, for which this feature flag is enabled, I see the session recording features. 

## Expected behavior

I should not see the session recordings option.

## How to reproduce

Sign up/in as someone not in the posthog team cohort and you'll see that the flag applies to you.

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

## Additional context

This feature is so cool though! I can see so many ways to make the product better with it.

Random other thing: the "skip inactive" toggle doesn't seem to work though. 

![2020-10-13 10 24 28](https://user-images.githubusercontent.com/53387/95835663-cccc3300-0d3e-11eb-9de4-745c1a8ed62c.gif)

**Comment by macobo** [comment] 2020-10-13 08:28
Re skip inactive: It works, but has unintuitive semantics. Basically if there's no recording data for a period, it will speed through it faster, but e.g. mouse moves are counted as activity.

**Comment by mariusandra** [comment] 2020-10-13 08:39
I'm not sure if it does. I had to wait 25sec before anything happened. No mouse was moved in that time and the clock moved one second every one second...

**Comment by macobo** [comment] 2020-10-13 11:54
I managed to reproduce this by:

1. Logging out of main account
2. Logging in using my alt account, which is not under the relevant cohort
3. Verifying that `posthog.isFeatureEnabled('session-recording-player')` returns true
4. Going incognito, logging in as alt, verifying `posthog.isFeatureEnabled('session-recording-player')` returns true
5. Find my distinct id incognito. `posthog.persistence.props.distinct_id`
6. Find person with that distinct_id listed (main_email@posthog.com), 
7. Click delete all data
8. Refresh, verify `posthog.isFeatureEnabled('session-recording-player')` returns false (!)

What seems to be happening is that as I logged out -> in again, my two "distinct_id"s landed under the same person_id - one of whom is under the cohort, making me see the feature flag.

This is sort of sketchy, but unsure what to make of it. If there is a bug, then it's somewhere in how we handle merging people together or that we don't unidentify users after logging out.

**Comment by timgl** [comment] 2020-10-13 11:56
Ah yep, we need to call `posthog.reset()` when a user logs out.

**Comment by timgl** [comment] 2020-10-13 11:56
Ah yep, we need to call `posthog.reset()` when a user logs out.

**Comment by macobo** [comment] 2020-10-13 11:58
Ack, thanks for the context. Handling!

I wonder whether we'll need to document this somewhere about feature flags - I think our users might run into similar issues with feature flags.

**Comment by mariusandra** [comment] 2020-10-13 12:00
I had a conversation via e-mail with a user who was having issues with this.

The logout event could happen from wherever (e.g. 1h timeout) and it was hard for posthog-js to know when to stop associating the session with the user. We should have some recipes for dealing with these case. 

They were thinking of setting a cookie "LOGOUT_PH=TRUE" after a logout, which the frontend would pick up and call `reset()` accordingly. Not sure what route they went with in the end.

I think a simpler option is possible, something like:

```js
const user = {user.from.django.or.wherever}

if (posthog.get_user_shomehow() != user) {
  posthog.reset()
}
```

Not sure of the details here.

**Comment by timgl** [comment] 2020-10-13 12:00
[It is!](https://posthog.com/docs/integrations/js-integration#reset-after-logout)

**Closed** 2020-10-15 07:56 UTC
Labels: bug
