### ISSUE TITLE
Define calculated events right from the live event table

### ISSUE THREAD

**Issue by deepskydata** [PostHog/posthog#11798] opened 2022-09-13 07:01 UTC
I often check incoming auto captured data in the live table and would love an option to select an event and based on it create a calculated event.

**Comment by pauldambra** [comment] 2022-09-13 07:12
![Screenshot_20220913-081036](https://user-images.githubusercontent.com/984817/189834391-10c7c2c3-3206-405d-a702-6f893cf1852f.png)

Looks like we've missed a rename here.

You can create calculated events by clicking on the kebab menu at the end of each row in the table and selecting "create action from event"

But this should say "create calculated event from event"

**Comment by deepskydata** [comment] 2022-09-13 07:15
Nice! - The issue was different. On my screen, the kebab menu was not visible because the table was cut off.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/95442831/189835296-0bb49205-a72b-484d-ae0e-ab0c5320c52e.png">

**Comment by pauldambra** [comment] 2022-09-14 11:57
I'll close this since the issue is resolved for you.

But tag @mariusandra and @clarkus so they know about this confusion for the ongoing table work

**Closed by pauldambra** 2022-09-14 11:57 UTC
Labels: bug, feature/data-management
