### ISSUE TITLE
Posthog Installation gives RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DishantPal** [PostHog/posthog#18335] opened 2023-11-02 08:23 UTC
So I have setup selfhosted posthog and then integrated into a Wordpress site. 

Now sometimes I'm noticing that in console, I'm getting the following error:
https://img.enacton.com/ShareX/2023/11/rCJrW4wgYD.png

There are so many such errors in the console.

## Environment
- PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]

Thanks!

**Comment by pauldambra** [comment] 2023-11-02 16:43
Hey Dishant,

You can see in the screenshot an error "posthog has already been downloaded once" this tends to point to an implementation error.

Is the site in question public? It's hard to debug from minified JS in a screen shot 😊

**Comment by gordalina** [comment] 2024-02-14 22:05
@pauldambra I'm facing the same issue in this website: https://smstoslack.app

**Comment by pauldambra** [comment] 2024-02-14 22:20
Hey @gordalina 

<img width="744" alt="Screenshot 2024-02-14 at 22 16 55" src="https://github.com/PostHog/posthog/assets/984817/b56aa646-6e08-4b5f-9d11-77d0997a82c7">

And the same error about posthog already having been downloaded once. That's always an implementation error. 

When I look in the HTML of the site you have the PostHog snippet included twice. You should only include the snippet once :)

**Comment by pauldambra** [comment] 2024-02-14 22:22
I didn't realise this was still open. I'll close this issue since it's an implementation error not an error in PostHog

**Closed by pauldambra** 2024-02-14 22:22 UTC
Labels: bug

**Comment by gordalina** [comment] 2024-02-15 01:01
It was an implementation error, thanks!

**Comment by earnold** [comment] 2024-03-28 14:40
For anyone using Rails who runs across this, the issue is the way that Posthog interacts with Turbo. You can see that referenced here: https://github.com/PostHog/posthog-js/issues/666

**Comment by sergiotapia** [comment] 2024-07-20 17:26
Thank you so much @earnold
