### ISSUE TITLE
Events and properties missing from dropdowns

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3308] opened 2021-02-11 11:47 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

A lot of users have reported their events as missing from the actions/events dropdown, and properties missing from filter dropdowns. I'd attributed this to past releases, but it seems to still be happening, including on Cloud.

On the events side, if you create an action from the event, then everything is fine. I've also seen events appear on the dropdown yet yield no data, but an action matching that event exclusively gives the right data. 

## Expected behavior

Dropdowns should be populated with all events and properties.

Events and actions from an event should have the same behavior. 

## How to reproduce

1. 
2.
3.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment] 2021-02-13 09:43
Bumping this as it's affecting a lot of users and preventing them from doing analytics

**Comment by razorinc** [comment] 2021-02-13 16:45
I'd say that this is a duplicate of #3260 I just added here to keep consistency of feedback and to have more intel on the issue.

**Comment by yakkomajuri** [comment] 2021-02-13 17:12
Somewhat - I did kind of batch two issues here.

Another problem not covered in #3260 is the events missing from the events dropdown, which is separate from the properties dropdown

**Comment by mariusandra** [comment] 2021-06-15 10:13
I assume this P0 bug from February is fixed now.

**Closed by mariusandra** 2021-06-15 10:13 UTC
Labels: P0, bug
