### ISSUE TITLE
Bug with contains filter in array-based attributes

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2301] opened 2020-11-10 06:42 UTC
## Bug description

When filtering insights by active feature flags, and trying to select a single feature flag (by using a `contains` selector), events are not being correctly filter (i.e. no events are returned). This presumably happens because the `active_feature_flags` attribute is stored as an array and the operator does not work properly on CH.

## Expected behavior

Relevant events should be loaded.

## How to reproduce

1. Create an insights graph, filter by "Active feature flags" using a contain selector.

Alternatively, just open [this graph](https://app.posthog.com/insights?actions=%5B%7B%22id%22%3A1578%2C%22name%22%3A%22created%20action%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&events=%5B%5D&new_entity=%5B%5D&interval=week&date_from=-90d&breakdown=false&breakdown_type&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22actions-ux-201012%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D).

## Environment

Cloud latest version.

#### *Thank you* for your bug report – we love squashing them!

CC @timgl

**Comment by EDsCODE** [comment] 2020-11-30 19:40
Just checked this and it seems the filter does work. If you create the graph linked using pageviews instead, [it shows](https://app.posthog.com/insights?actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&new_entity=%5B%5D&interval=week&date_from=-90d&breakdown=false&breakdown_type&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22actions-ux-201012%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D) filtered events.  

I verified manually too. We handle the contains operator by string matching so it'll work even if the property is an array because we'll just treat the array as a string and match it to the argument as shown below.

I think the issue is with `created action` action itself probably matching something different when the feature flag is active
<img width="1299" alt="Screen Shot 2020-11-30 at 2 32 31 PM" src="https://user-images.githubusercontent.com/13127476/100655688-a297fa00-3319-11eb-986c-4e34693c5446.png">

**Comment by paolodamico** [comment] 2020-11-30 21:27
You're right, it seems like a different problem then, but as `created action` only matches client-side events, it looks like we do have some bug here (as the active feature flags prop should be present), right?

**Comment by EDsCODE** [comment] 2020-12-01 15:11
@paolodamico i agree. we'll have to look into the action itself and check out why they're not associating with events that have the flags. 

tagging @timgl so you know we did some initial digging here. i can pick it back up later in the week when i get #2578 and #2460 merged

**Comment by paolodamico** [comment] 2020-12-01 22:15
I managed to narrow down the problem, the filtering works after removing the regex filter, so the problem is specifically with using these kind of filters. Related to this, I couldn't set the regex filter as matching group, see #2613

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5864173/100803231-71d6c400-33f0-11eb-999f-d60a09c642ce.png">

**Comment by EDsCODE** [comment] 2020-12-08 01:54
I fixed #2613!

Could you send a link for how the regex filter above is failing? I tried the filtering and it seems to work unless i'm looking at it wrong

**Comment by paolodamico** [comment] 2020-12-08 16:58
Sure thing, here's the [relevant action](https://app.posthog.com/action/1578), & the errored [insights graph](https://app.posthog.com/insights?insight=TRENDS&interval=day&display=ActionsLineGraph&actions=%5B%7B%22id%22%3A1578%2C%22name%22%3A%22created%20action%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&events=%5B%5D&new_entity=%5B%5D&properties=%5B%7B%22key%22%3A%22%24active_feature_flags%22%2C%22value%22%3A%22actions-ux-201012%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22event%22%7D%5D)

<img width="1271" alt="" src="https://user-images.githubusercontent.com/5864173/101515661-35511e00-3944-11eb-860a-b8fac26c3d42.png">

**Closed** 2020-12-09 18:19 UTC
Labels: bug

**Comment by paolodamico** [comment] 2020-12-14 17:00
Confirmed this is fixed! Thanks @EDsCODE!
