### ISSUE TITLE
Insight trends with a lot of dates and breakdown lines are SLOOOOW

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7751] opened 2021-12-16 14:23 UTC
## Bug description

This slowness is on the latest M1 Pro Mac on [this page](https://app.posthog.com/insights/TviShYmw?insight=TRENDS&display=ActionsLineGraph&interval=day&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&properties=%5B%5D&filter_test_accounts=true&legend_hidden=true&date_from=yStart&breakdown=%24browser&breakdown_type=event) and others like it. Later in the gif I keep trying to scroll left-right on the table, but nothing happens. Also no sidebar highlight are shown.

![2021-12-16 15 21 31](https://user-images.githubusercontent.com/53387/146389306-1cc85840-a43a-496f-a629-a3867577f166.gif)

## Expected behavior

It shouldn't lag this much

## How to reproduce

1. Open new insight -> trends
2. Select ~365 days, by day
3. Apply a breakdown that gives you 10+ rows
4. Die of old age

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

I think the table below makes everything really slow

**Comment by Twixes** [comment] 2021-12-16 14:28
I think this may be duplicate of #7543.

**Closed** 2021-12-21 22:19 UTC
Labels: bug, trends, team-core-experience, insights
