### ISSUE TITLE
Posthog freezes with no sign of error

### ISSUE THREAD

**Issue by zzh8829** [PostHog/posthog#3819] opened 2021-03-30 19:43 UTC
## Bug description

Posthog freeze with no sign of error. Logs and metrics all look normal but requests are hanging.

## How to reproduce

1. wait long enough posthog will freeze
2.
3.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: docker:latest

**Comment by timgl** [comment] 2021-04-01 13:18
@zzh8829 Thanks for raising this. Would you mind elaborating a little bit?

- Is it the interface that is freezing (ie you can't click anything anymore) or is it queries that are timing out?
- What browser are you on?
- What page are you on when it freezes?

Thanks!

**Comment by zzh8829** [comment] 2021-04-01 16:45
Hello, so by freezing I mean the requests to posthog will timeout and won't return anything. Don't think it's related to the browser since we tried making api call, curl, and opening posthog UI directly none of them work. Everything returns normal if we restart our posthog instance, there is no error log or anything obvious like that.

**Comment by zzh8829** [comment] 2021-04-01 16:47
here is a screenshot of the system status page if that helps 
![image](https://user-images.githubusercontent.com/2136136/113327014-4648e500-92cf-11eb-8736-76defe961cd1.png)

**Comment by timgl** [comment] 2021-04-01 16:48
That's helpful thanks. How are you deploying posthog? docker-compose?

**Comment by zzh8829** [comment] 2021-04-01 21:43
We deployed it using docker container on https://zeet.co the setup is pretty standard with IS_DOCKER=true and DISABLE_SECURE_SSL_REDIREC=true since it's behind a reverse proxy

**Comment by paolodamico** [comment] 2021-04-01 22:40
Hey @zzh8829! Have you set up the proxy config on your instance (i.e. `IS_BEHIND_PROXY` and `TRUSTED_PROXIES`)? https://posthog.com/docs/configuring-posthog/running-behind-proxy

Another thing that would be helpful to try is if you can reach the PostHog app directly from the container using a curl command or similar tool, that way we can narrow down if the problem is with the PostHog app or some other connection problem.

It might be faster if you join us on [Slack](https://posthog.com/slack), that way we can try a bunch of stuff faster to troubleshoot this.

**Comment by boldtrn** [comment] 2021-04-02 14:52
Just wanted to add that I face the same issue. Every few days my Posthog instance goes down. Looking at the processes it is still running and I can also see DB queries happening.

I haven't tried accessing it locally yet. I also use the Docker container self-hosted.

I have set IS_BEHIND_PROXY. The issue occurs since 1.23.0 or 1.23.1.

**Comment by boldtrn** [comment] 2021-04-03 16:31
Ok so this just happened again for my instance, here are some logs, in case this helps:

```
XXXXXXXX - - [03/Apr/2021:07:08:41 +0000] "POST /e/?compression=gzip-js&ip=1&_=XXXXXX HTTP/1.0" 200 13 "-" "Mozilla/5.0 (Linux; Android 7.0; BAH-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/XXXXXXXX Safari/537.36"
XXXXXXXX - - [03/Apr/2021:07:08:41 +0000] "POST /e/?compression=gzip-js&ip=1&_=XXXXXXX HTTP/1.0" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/XXXXXXXXX Safari/537.36 Edg/XXXXXXXXX"
XXXXXXXX - - [03/Apr/2021:07:08:41 +0000] "POST /_ignition/execute-solution HTTP/1.1" 301 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0"
[MAIN] ⏲ Performing periodic MMDB staleness check...
[MAIN] ❎ MMDB staleness check completed, no update was needed
[MAIN] ⏲ Performing periodic MMDB staleness check...
[MAIN] ❎ MMDB staleness check completed, no update was needed
[MAIN] ⏲ Performing periodic MMDB staleness check...
[MAIN] ❎ MMDB staleness check completed, no update was needed
```

These seem to happen supper frequently for posthog_db:
```
2021-04-03 06:45:59.686 UTC [5592] ERROR:  duplicate key value violates unique constraint "unique distinct_id for team"
2021-04-03 06:45:59.686 UTC [5592] DETAIL:  Key (team_id, distinct_id)=(1, kv1181606272094249) already exists.
2021-04-03 06:45:59.686 UTC [5592] STATEMENT:  INSERT INTO posthog_persondistinctid (distinct_id, person_id, team_id) VALUES ($1, $2, $3) RETURNING *
```

When I try to connect locally on the server to the docker container:
```
curl localhost:8000
curl: (56) Recv failure: Connection reset by peer
```

**Comment by boldtrn** [comment] 2021-04-03 16:45
Not sure if it helps, but when Posthog goes down I see a spike in file usage (Friday afternoon and Saturday morning):

![Screenshot 2021-04-03 at 18 43 14](https://user-images.githubusercontent.com/1553525/113485150-8a451100-94ac-11eb-9062-e1971cf03cd2.png)

**Comment by zzh8829** [comment] 2021-04-03 17:12
we also see the same database key violation very often don’t know if it’s related to this freezing issue tho. 

also same with boldtrn i do not believe this has anything to do with proxy, it appears that the container just stops accepting requests

**Comment by paolodamico** [comment] 2021-04-06 01:01
Hey @boldtrn! Hmm what seems to be going on is that your instance gets under some heavy load and then logically takes time to respond (probably up to the point of timeouts). Based on the pattern, it could be that you have a spike in traffic periodically or you do a lot of querying. Does this ring any bells?

Do you have any metrics breakdown on memory / CPU usage on your web/worker/plugins resource usage vs. your database? I suspect your database is the bottleneck here. What kind of resources do you have allocated for your database? Also, what's your rough monthly event volume?

One thing that could help is the refactor coming in the new release (#3866) which will greatly unload the resources required to load PostHog to avoid freezing the entire thing. Do you have a ton of events (as in different event names) and/or properties? Could you check what's the payload size of the `/api/user` request?

I'll open an issue to investigate those unique constraint violations but as @zzh8829 mentioned, I don't think it's related.

**Comment by boldtrn** [comment] 2021-04-06 08:47
Thanks for the detailed reply @paolodamico.

> Do you have any metrics breakdown on memory / CPU usage on your web/worker/plugins resource usage vs. your database?

Both run on the same machine, so I have means to show separate usage. At least the overall usage was not too high, so the server was not constantly at 100% CPU.

> Based on the pattern, it could be that you have a spike in traffic periodically or you do a lot of querying. Does this ring any bells?

I don't really query a lot. I have a few actions, event filters and cohorts that are recalculated (every 5 minutes?). Generally we don't really have massive traffic spikes, more traffic during the day than at night, but not like everyone rushing in at a certain time. I don't visit the Posthog dashboard daily, so at least there is not a lot of manual querying.

> Also, what's your rough monthly event volume?

I might have been simple overload yes. I rescaled the and so far it didn't freeze completely. I had a few cases where it was shortly unavailable. But nothing too critical.

We do have a lot of events, and we had quite some increase of events recently. I can't give you an exact number of events (not sure how to count them :)). Here is a screen of the status page, that's a few months worth of data. And the number of events increased recently.

![Screenshot 2021-04-06 at 10 00 44](https://user-images.githubusercontent.com/1553525/113681892-d1a4ea80-96c2-11eb-80ae-41cd7efbcc05.png)

Right now the Posthog instance is still running on a virtual server and I was thinking of upgrading it to a dedicated server, with a lot more computation power. 

> What kind of resources do you have allocated for your database?

I am actually using the defaults provided by Posthog. 

The server itself had:
4 vcpus
8 gb RAM

Now after rescaling it has
8 vcpus
16 gb RAM

I am thinking of upgrading it to dedicated server with a "Ryzen 5 3600" or something like that. Not sure if this would be the way to go? Or rather hope that performance is improved with new features at Posthog?

> Do you have a ton of events (as in different event names) and/or properties?

I do have like 30 custom events and I do set properties for these events, to further allow filtering them down. All (or most) events are assigned to a cohort.

> Could you check what's the payload size of the /api/user request?

I am not sure how to do that, could you provide me some pointers on how to do that.

When I visit my Posthog Dashboard, there is a request to api/users, the request size is 10.1kb gziped and 113kb resource size, according to my browsers dev tools.

**Comment by paolodamico** [comment] 2021-04-09 19:03
Hey @boldtrn! This context is very helpful! Here are my thoughts,

1. While there definitely seems to be something that changed recently on our end that is affecting this (as this is happening to other users; we are already investigating further), based on your event volume it looks like you may be reaching the limits of what Postgres can do. As a rule of thumb, anything higher than 5M events/month will not work on Postgres. We're just about to open an option to get a free license to run PostHog with ClickHouse, would this seem like a right fit (see https://github.com/PostHog/posthog.com/pull/1201)? Please be mindful of the expertise required to run it.
2. I think rather than a dedicated server to run your entire infrastructure, it might be more helpful to spin off your database into it's dedicated instance with resources provisioned just for it. Ideally we would recommend using something like RDS or DO's Postgres, as these are well tested services that will handle all the nitty gritty details of running a DB cluster, plus any low level optimizations that can help Postgres run smoothly. From what we've seen before, the additional benefit of splitting your DB is that the rest of the infrastructure may need fewer resources in total than before).
3. For context, it doesn't look like any other elements are out of norm here (e.g. querying, traffic spikes, cohorts, actions, ...) so worth considering the points above.

**Comment by boldtrn** [comment] 2021-04-10 15:56
Thanks a lot for the detailed answer and the offer for the ClickHouse upgrade @paolodamico.

1. Switching to ClickHouse sounds interesting. I do have some experience hosting different kinds of applications. Is there documentation on how to setup ClickHouse, so that I can check if it's something I feel comfortable with? I already manage too many servers ;).
2. I already switched to a dedicated server a few days ago. So far I haven't had any downtimes. Recalculating the dashboard still requires some time, but overall it feels a lot better compared to the virtual server before, so I guess there was definitely some kind of bottleneck.

**Comment by paolodamico** [comment] 2021-04-12 18:45
Hey @boldtrn! We don't have docs on CH just yet but they're coming pretty soon. Once they do let me know if you're interested in a license. Re 2, that's great! Glad to hear that, do let us know how your experience goes after upgrading to 1.24

**Comment by boldtrn** [comment] 2021-06-25 16:27
Sorry for the late reply, I tried to see if it would work also after upgrading to 1.25, but I have to say that my Posthog instance seems to struggle quite a lot with all the events and many of my insights can't be calculated apparently as they often report 0, but when I try to let it recalculate often enough it sometimes seems to produce a number. 

So I would be interested in switching to CH. Maybe there is some documentation already or any other hints you could provide on how I can switch?

**Comment by boldtrn** [comment] 2021-06-25 16:29
My database grew quite a bit as well, from about 50gb to 150gb.

![Screenshot 2021-06-25 at 18 28 14](https://user-images.githubusercontent.com/1553525/123456483-2d588300-d5e3-11eb-9d62-1c3d8b81ac5c.png)

**Comment by paolodamico** [comment] 2022-02-23 15:39
The app has significantly evolved and this now seems outdated. I'll close it but feel free to open a new issue if there's still something that fails.

**Closed by paolodamico** 2022-02-23 15:39 UTC
Labels: bug
