### ISSUE TITLE
Insights > Stickiness > Pie - shows empty chart and NaN

### ISSUE THREAD

**Issue by buwilliams** [PostHog/posthog#3946] opened 2021-04-12 14:50 UTC
## Bug description

Found while testing Stickiness. The page is showing users NaN but it should be clear there are no results to show.

## Expected behavior

- Displays a message that there are no results to show.
- Shouldn't show `NaN`

## How to reproduce

1. On Actions & Events: select `$pageview` and `total volume`
2. Select `Pie` and `Last 30 days`
3. Result is the attached screenshot

## Environment

- [ ] playground.posthog.com

<img width="1436" alt="Screen Shot 2021-04-12 at 10 44 25 AM" src="https://user-images.githubusercontent.com/243320/114414312-b3d0fd00-9b7c-11eb-8836-615647b19ecf.png">

**Comment by Twixes** [comment] 2021-04-29 12:43
Hm, looks like this is actually a duplicate of #3469.

**Closed by Twixes** 2021-04-29 12:43 UTC
Labels: UI/UX, good first issue, release-1.24.0
