### ISSUE TITLE
Session replays showing blank screen

### ISSUE THREAD

**Issue by ajaen4** [PostHog/posthog#21825] opened 2024-04-24 17:42 UTC
## Bug description

The session replay functionality has stopped working. It was working 4 h ago. Any session replay I try to watch shows a white screen with a cursor in the top left corner:
<img width="1728" alt="Captura de pantalla 2024-04-24 a las 19 39 37" src="https://github.com/PostHog/posthog/assets/26901448/1cbe406d-eb02-4da5-bf45-ca843a71cb44">

This is an example link of when it occurs:
https://eu.posthog.com/project/16888/replay/recent?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-7d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22console_search_query%22%3A%22%22%7D&sessionRecordingId=018f1122-aed2-7fdf-b5c6-a96467ada850

## How to reproduce

1. Open session replay
2. Play any recording

I am on version 1.108.3 of the SDK. Let me know if I can help out with more info.

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f112e-16ab-7d42-9de0-8ce33b8222ff?t=54 (at https://eu.posthog.com/project/16888/replay/recent?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-7d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22console_search_query%22%3A%22%22%7D&sessionRecordingId=018f103b-ab86-77bf-8906-9273a42e8949#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgEU/018dd596-3a65-0000-66b9-7c8d9180bb49 (Project: 16888)
Sentry: http://go/sentryEU/16888
```

**Comment by daibhin** [comment] 2024-04-24 18:04
This is actually a duplicate of https://github.com/PostHog/posthog/issues/21791

The issue has now been resolved in production

**Closed by daibhin** 2024-04-24 18:04 UTC
Labels: bug
