### ISSUE TITLE
Events is not being sent

### ISSUE THREAD

**Issue by shvatsky** [PostHog/posthog#23215] opened 2024-06-25 06:49 UTC
## Bug description
Hi folks

We are experiencing some descreasing in number of events starting from June 21st. 

Let's take a funnel of our credit product as example. We are sending __pass_ and __view_ events from each step of the funnel meaning the events of viewing and passing the step. We are doing that to be able to analyze if we have some drop-offs in between of passing one screen and viewing the next one. 

For major number of steps we have 95% or higher conversion rate between passing one screen and viewing next one which seems normal. But starting June 21st we have seen significant decreasing of such conversions. One of the examples:
![Снимок экрана 2024-06-25 в 11 41 30](https://github.com/PostHog/posthog/assets/106468283/ce51c9fe-9ada-4f9d-a760-d6b83077d2f5) 
(feel free to reach me for more examples).

We didn't release anything regarding analytics implementation on June 21st as we didn't do any other possible changes that might affected on data. So please could you help me to check if it is the issue from PostHog side?

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: 
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01904dfa-c784-73ee-805e-1d270e9001fe?t=2892 
Admin: http://go/adminOrgUS/01863530-c392-0000-3ede-df951021da26 (Project: 20595)
Sentry: http://go/sentryUS/20595
```

**Comment by MarconLP** [comment] 2024-06-25 09:41
Duplicate of ticket [ZEN-15070](https://posthoghelp.zendesk.com/agent/tickets/15070)

**Closed by MarconLP** 2024-06-25 09:41 UTC
Labels: bug
