### ISSUE TITLE
Groups Feedback: Enable search / filtering on group tabs

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#7941] opened 2022-01-07 10:43 UTC
## Is your feature request related to a problem?

On the persons tab, it is possible to search for a person or add a filter to find a person.

![image](https://user-images.githubusercontent.com/11272509/148532376-ca745faa-e3a8-4405-927f-d4a0dc55abbd.png)

![image](https://user-images.githubusercontent.com/11272509/148532401-2339ca02-caa4-4d53-9d09-6b12af2ac15c.png)

## Describe the solution you'd like

Enable this functionality for the groups tabs too.

## Describe alternatives you've considered

Use the browser CTRL+F.

## Additional context

CC @macobo - I am adding some early feedback on groups here.

**Comment by macobo** [comment] 2022-01-07 11:06
:+1: for this

Duplicate of https://github.com/PostHog/posthog/issues/7265

**Comment by neilkakkar** [comment] 2022-07-27 10:24
Closing as duplicate of https://github.com/PostHog/posthog/issues/7265

**Closed by neilkakkar** 2022-07-27 10:24 UTC
Labels: enhancement, feature/group-analytics
