### ISSUE TITLE
Retention graph overflow bug

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#9526] opened 2022-04-25 22:42 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

User is unable to scroll sideways to view the entire retention graph for graphs that overflow

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by benjackwhite** [comment] 2022-05-12 10:44
I think this is fixed! Since the addition of the (feature-flagged) new Editor Panels, one of the fixes I made was to exactly this. It fixes it both in the new and the old view.

@liyiy looks good based on an Inisght you created around the same time as this issue. Will close this but feel free to re-open if the issue is not what I thought it is :D 

https://app.posthog.com/insights/9xxlokwG

**Closed by benjackwhite** 2022-05-12 10:44 UTC
Labels: bug
