### ISSUE TITLE
Saving insight with no data allowed in some cases

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#15409] opened 2023-05-05 17:30 UTC
See an example here of a user that managed to click "Save" on an insight with no data, which then wasn't actually saved.

https://posthoghelp.zendesk.com/agent/tickets/2536

**Comment by yakkomajuri** [comment] 2023-05-08 11:17
@thmsobrmlr

**Comment by Arun-chaitanya** [comment] 2023-07-24 18:26
@yakkomajuri if possible can you tell me some steps to reproduce it and I can solve it for you guys? Because I am trying to reproduce this for you and I am NOT able to save any insight with no data.

**Comment by thmsobrmlr** [comment] 2023-07-24 22:53
Hey @Arun-chaitanya, I just had a look at the mentioned Zendesk ticket. Basically when you'd edit an existing insight with filters so restrictive that there are no results any more, the insight had shown previously cached results. This has been solved meanwhile. Closing this :)

**Closed by thmsobrmlr** 2023-07-24 22:53 UTC
Labels: bug, feature/saved-insights, feature/insights
