### ISSUE TITLE
Create action from events page

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#880] opened 2020-05-27 18:11 UTC
**Is your feature request related to a problem? Please describe.**
Creating actions is rather unfriendly/unclear without the toolbar for frontend elements. 

**Describe the solution you'd like**
I want to be able to just select things on the list of event and create actions directly from there. Right now to make an action from an autocaptured element you have to go to the create action page and either use the toolbar editor or enter a bunch of fields that are pretty hard to figure out correctly

**Describe alternatives you've considered**
Make the inputs easier to understand so that you can manually enter

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment] 2020-06-02 09:21
Duplicate of #181 (yes, really) but will add that one to the list

**Closed** 2020-06-02 09:21 UTC
Labels: enhancement
