### ISSUE TITLE
Annotations not displaying correctly in saved insight

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#11136] opened 2022-08-04 10:35 UTC
## Bug description

When viewing [this saved insight](https://app.posthog.com/insights/CsiAStvC), there's a large horizontal scrollbar because the annotations are entirely off the screen (on the right).

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/154479/182826658-09f05f3c-0eb9-485e-86a6-e9262a2183bb.png">

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/154479/182826767-be97aafc-ccab-4471-b1e0-32eec1305b4d.png">

## How to reproduce

1. View [this insight](https://app.posthog.com/insights/CsiAStvC) in Chrome

No console errors.

**Comment by clarkus** [comment] 2022-08-22 21:42
Related and possibly the same issue as https://github.com/PostHog/posthog/issues/9511

**Comment by clarkus** [comment] 2022-08-22 21:42
Possibly a duplicate of https://github.com/PostHog/posthog/issues/7841

**Closed** 2022-09-06 10:48 UTC
Labels: bug, feature/saved-insights, feature/annotations
