### ISSUE TITLE
Events & actions huge load

### ISSUE THREAD

**Issue by aratnikovmxmgt** [PostHog/posthog#8514] opened 2022-02-09 09:26 UTC
## Bug description

If I try to visit Events & actions tab in posthog I can immediately see how my disk is trying to process it. After about 10 seconds I can see my events and it works as expected. And If I'm clicking on 'There are  new events. Click here to load them' posthog loads them instantly.

But somehow things changed and now after visiting Events tab posthog breaks. In my Clickhouse I can see that it still working on some query by disk loading (`iostat -4` for example). In Clickhouses query logs I can see strange query:

```
SELECT
    uuid,
    event,
    properties,
    timestamp,
    team_id,
    distinct_id,
    elements_chain,
    created_at
FROM
    posthog.events
where team_id = 1
AND timestamp > '2021-02-04 17:00:44.158000'AND timestamp < '2022-02-04 17:00:48.206451'
ORDER BY toDate(timestamp) DESC, timestamp DESC LIMIT 101
```
1. No space between conditions
2. Time range is a year. We have about 110 GB of data and it seems posthog can't wait much longer and stops working.

I've tried to upgrade to 1.32 version, but loading Events tab process still breaks with 502 error. Now I've downgraded posthog to 1.31 and in button 'Customize columns' I've pressed 'Reset to default' and it works well. If I will change the version to 1.32 - this error will remain.

## Expected behavior

Fields for selecting the time range in Events & actions tab. Set default value to 1 hour or something like that.

## How to reproduce

Not sure how to do it. In my case it happened randomly, but now repeats after upgrade to 1.32 

## Environment

Self-hosted PostHog (ClickHouse-based), version/commit: [release-1.31.1](https://hub.docker.com/layers/posthog/posthog/release-1.31.1/images/sha256-d825dd3eec25935089800d329eb6d82a77bcf565de8d24e8e4db1a1b036b6ab3?context=explore)

**Comment by neilkakkar** [comment] 2022-02-10 08:47
Thanks @aratnikovmxmgt, I'm looking into this!

(dupe of #8187 )

**Closed** 2022-02-11 10:43 UTC
Labels: bug, team-core-analytics
