### ISSUE TITLE
New funnels - Bug & improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5001] opened 2021-07-06 06:35 UTC
Documenting here non-blocking bugs and experience improvements on the new funnel visualization, including latest changes from #4965. Keeping this separate issue as to not block PRs.

~1. The initial state of funnels is strange. Perhaps is the fact we automatically calculate the funnel with a single step. Maybe worth not computing automatically if the funnel is a single step and/or opening the default?~
<img width="700" alt="" src="https://user-images.githubusercontent.com/5864173/124550023-558c8100-de30-11eb-89f1-d70af6c67846.png">

~2. If the action/event name is too long, the action icons for each step gets cut off to the next line.~
<img width="376" alt="" src="https://user-images.githubusercontent.com/5864173/124550928-b7011f80-de31-11eb-88a2-9ae8a18c716b.png">

3. We can optimize the display settings for time to only display the two most significant units. For example, if we're talking about hours and minutes, seconds is probably not as relevant. **EDIT:** still happening when showing overall conversion.

<img width="204" alt="" src="https://user-images.githubusercontent.com/5864173/124553554-29273380-de35-11eb-954c-434fd0edbfcc.png">

4. There's some strange behavior with manual calculation vs. auto-caculate. Changing the timeframe calculates the funnel automatically, but if you had some previous changes in the funnel, it's confusing. If we're keeping the manual calculation, we should not auto-calculate if the funnel is not shown.
![image](https://user-images.githubusercontent.com/5864173/124554758-9ab3b180-de36-11eb-9264-715e6e0bbcbf.gif)

~5. Event names and average times show in two lines when the funnel has multiple steps which looks a bit strange.~
<img width="859" alt="" src="https://user-images.githubusercontent.com/5864173/124584477-972f2300-de54-11eb-87e1-520ab8c89e8d.png">

6. The type of graph selector shows in multiple lines when the width is constrained. Perhaps here it's worth switching the visual element? Maybe the dropdown would go best here. CC @clarkus 
<img width="300" alt="" src="https://user-images.githubusercontent.com/5864173/124584585-b75ee200-de54-11eb-9b87-33f4890f83e6.png">

CC @samwinslow in case you have time to fix a few for tomorrow's tests.

**Comment by clarkus** [comment] 2021-07-06 20:31
> The initial state of funnels is strange. Perhaps is the fact we automatically calculate the funnel with a single step. Maybe worth not computing automatically if the funnel is a single step and/or opening the default?

The easiest change is probably to wait to calculate until at least two steps are identified. This might cause some drop-offs for posthog users, so we might also consider changing how we illustrate step 1. If we represent the total potential population and the conversion & drop-off rates for step 1, it might make that a more valuable default state. For example, for the given time frame you had 1,000 potential users, 300 users complete step 1 (sign up) at a 30% conversion rate / 70% drop-off rate. 

I feel like there's a lot of value to showing data as soon as possible in this process. As long as that initial state is valuable and informs the funnel the user is composing, then it could be worth trying. 

> Event names and average times show in two lines when the funnel has multiple steps which looks a bit strange.

The left-to-right layout is pretty rigid in terms of character lengths. When the step names exceed the available space, we're going to have to truncate the label and reveal the full name on hover via a tooltip. I think your point on only showing time specific to the two largest units makes sense... for example 2 hours 3 minutes, 4 days, 14 hours, 5 minutes 3 seconds, etc. We might also need to work out a time unit abbreviation pattern to make this more scalable.

> The type of graph selector shows in multiple lines when the width is constrained. Perhaps here it's worth switching the visual element? Maybe the dropdown would go best here. CC @clarkus

This component could work depending on the labels we use to describe the options. Is there anything we can do to simplify these labels? There are more than two options in the list, so we could change the component to a dropdown when in narrower view port sizes. That isn't great for discovery, but it might be enough to get us closer to launching the updated visualizations.

**Comment by samwinslow** [comment] 2021-07-07 11:53
@clarkus @paolodamico

- Step calculation: FWIW I think it's a feature, not a bug, that we show 100% on the first step, because a full-size bar gives a nice visual comparison for the other steps. If the first bar was partway filled I think its meaning would become ambiguous.
- Step calculation: Perhaps to make intended actions more clear when only 1 bar is shown, we can show a (+) button. We could also just always show this button. See rough mock below.

<img width="881" alt="Screen Shot 2021-07-07 at 7 48 18 AM" src="https://user-images.githubusercontent.com/4645779/124754246-fdb94d00-def7-11eb-98f5-563a6286cd15.png">


- Simplifying the chart type labels: How do you guys feel about this? I feel like these are already the terms we use internally to describe these features.

<img width="371" alt="Screen Shot 2021-07-07 at 7 44 03 AM" src="https://user-images.githubusercontent.com/4645779/124753661-41f81d80-def7-11eb-814b-84b4f8abe042.png">

- Titles: I think it's OK that titles continue onto 2+ lines. Especially with potentially long action names, or custom-defined step names, it only makes sense that we'd let it wrap. I have adjusted the title component so that the icon never appears alone on a line, but other than that I don't think we want to truncate the title because it would be an unfortunate compromise on UX for aesthetic reasons.

Totally agree re: all other points and have started working on #5018

**Comment by clarkus** [comment] 2021-07-07 16:36
>     * Step calculation: FWIW I think it's a feature, not a bug, that we show 100% on the first step, because a full-size bar gives a nice visual comparison for the other steps. If the first bar was partway filled I think its meaning would become ambiguous.

Yeah I think this has more to do with the user feeling like their queries are working and producing results. The pageview event is a great starting point because it really represents the entire potential audience. It's really showing that first transition step (step 2) that feels like the value point for users. 

>     * Step calculation: Perhaps to make intended actions more clear when only 1 bar is shown, we can show a (+) button. We could also just always show this button. See rough mock below.

I think this would be worth testing. My one reservation is that we're prompting for a step add in a place where you don't actually add steps. It might be confusing to click into the chart area and see the composer area update. 

>     * Simplifying the chart type labels: How do you guys feel about this? I feel like these are already the terms we use internally to describe these features.

I think this would be worth testing, as well. Seems like a good simplification but I'm wondering what a sample of users would say.

>     * Titles: I think it's OK that titles continue onto 2+ lines. Especially with potentially long action names, or custom-defined step names, it only makes sense that we'd let it wrap. I have adjusted the title component so that the icon never appears alone on a line, but other than that I don't think we want to truncate the title because it would be an unfortunate compromise on UX for aesthetic reasons.

I don't think it is aesthetics as much as it is alignment. We need to ensure all the bars start at the same relative offsets to ensure that it's straightforward to scan those values. If we allow for multi-line names, then we'd want to adjust the offset for all bars to start at the same point. It's also worth noting that in the left-to-right layout longer names are going to displace the chart content as they become more verbose, so while we can try to show more detail, at some point it's going to push chart content down and possibly displace those core metrics. 

A lot of our constraints are this 688px container for funnel visualizations. Other insights are using full page width containers, so I'd like to double back to that composition work at some point to ensure a more consistent experience across building insights. If funnels can have a full-width layout then the left-to-right layout becomes much more viable.

**Comment by paolodamico** [comment] 2021-07-08 12:37
Thanks for the work above, it's already looking much better!

My only outstanding concern is with the initial state which a user also reported as confusing. Think we can just have a nice empty state and as soon as you add a second step we show you the funnel?


Also reporting a few additional bugs.

~7. Date is improperly shown in conversion trends.~
<img width="263" alt="" src="https://user-images.githubusercontent.com/5864173/124921889-84d0f880-dfbe-11eb-9199-03bae808fa6e.png">

8. The person modal should actually scroll within it's own internal space and the footer be kept always visible (see mockups), so the footer actions are discoverable. CC @liyiy 

<img width="836" alt="Screenshot 2021-07-07 at 4 48 46 AM" src="https://user-images.githubusercontent.com/5864173/124922003-a6ca7b00-dfbe-11eb-978a-9108852ec12a.png">

9. ~Not sure if this is a backend or a frontend bug, but see this case where we're showing average time to convert in the first step (which doesn't make sense) and not on the second one. For consistency, I think we should also show something like "Not applicable" if a step is 0%, thoughts? CC @EDsCODE @neilkakkar~

<img width="1284" alt="" src="https://user-images.githubusercontent.com/5864173/124922145-d2e5fc00-dfbe-11eb-933f-911e80c13f02.png">

10. ~Funnels in dashboards look strange IMO, like they're cut off (at the bottom) or something. User also reported that it's "a shame" that you lose the other conversion numbers, and didn't have tooltips with more info either. Thoughts @clarkus ?~

<img width="645" alt="" src="https://user-images.githubusercontent.com/5864173/124922521-31ab7580-dfbf-11eb-86a9-a7c39b1b236c.png">

11. We should show some visual indication when the funnel can be scrolled, particularly in dashboards. If the exact conditions aren't met for the design to be shown cut off, you'd never guess the funnel had more steps.

**Comment by liyiy** [comment] 2021-07-08 14:29
for point 8 just got this up #5040, apologies for the delay 

for point 10, do we want to be able to also open up the persons modal from the dashboards view? Currently on the dashboard view for trends graphs, you can see how many users but you can't open the modal for it from there

**Comment by paolodamico** [comment] 2021-07-08 15:23
Re 10 @liyiy. I think to keep this consistent we shouldn't do the person modal click for now in dashboards. We can iterate this later if it makes sense.

**Comment by clarkus** [comment] 2021-07-08 18:35
> My only outstanding concern is with the initial state which a user also reported as confusing. Think we can just have a nice empty state and as soon as you add a second step we show you the funnel?

I put together an empty state for funnels at https://github.com/PostHog/posthog/issues/3982#issuecomment-876656269. Clicking on the large button in the empty state would trigger the step adding workflow. 

<img width="1280" alt="empty state - need more steps" src="https://user-images.githubusercontent.com/254612/124973534-81e6ff80-dfe0-11eb-933d-93e0b807515a.png">

**Comment by paolodamico** [comment] 2021-07-20 17:53
Issue has been updated, only a few more outstanding issues to go

**Comment by paolodamico** [comment] 2021-07-20 17:54
Issue has been updated, only a few more outstanding issues to go. @samwinslow could use your help with no. 4, as you have better context on this one

**Comment by alexkim205** [comment] 2021-07-26 18:23
I believe the outstanding (not crossed out) issues—3, 4, 6, 8, 11—have all been addressed or been changed quite significantly since the release. Is it safe to say that we can close this one out (or label stale)?

**Comment by samwinslow** [comment] 2021-07-26 20:26
I agree that much of what's here is outdated — would like to add one bug re: persons modal, however:

![Screen Cast 2021-07-26 at 3 13 59 PM](https://user-images.githubusercontent.com/4645779/127054287-6a531c80-85ad-46de-ac09-86045b6489d9.gif)

- Step count changes to 0 after searching.
- Search button is blue-on-blue so the icon is not visible.

**Comment by alexkim205** [comment] 2021-07-27 01:29
Fixed bugs here - https://github.com/PostHog/posthog/pull/5334

I think all bugs and improvements have been addressed, so I'll close this one out. Feel free to lmk if you see otherwise!

**Closed by alexkim205** 2021-07-27 01:29 UTC
Labels: bug, core-experience, enhancement, funnels
