### ISSUE TITLE
Denormalize high volume clickhouse properties into columns

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2900] opened 2021-01-08 19:45 UTC
For most queries on clickhouse, we need to read the entire properties column for every event. As an example, one clients average property field is 1000 characters, but a 7-day query means we're reading 212gb just for the property field.

We should denormalize property keys with lots of events into their own fields.

Questions
- Does normalizing these fields into Arrays have the same effect?

Suggested approach (I'm sure there's better ones):
- A management command that
  - identifies high volume property keys
  - creates the column
  - fires off whatever clickhouse command to fill that column (@fuziontech what does that look like?)
- Add those properties as an environment variable
- Whenever we run queries, if the property is in the env variable we query it directly rather than via properties

Thoughts @EDsCODE @fuziontech

**Comment by timgl** [comment] 2021-01-08 20:41
After discussion on slack, we'll manually figure out which properties to denormalize and create the columns, but we'll do the rest of these async

**Comment by macobo** [comment] 2021-09-15 19:46
Duplicate of materialized columns changes it seems

**Closed** 2021-09-15 19:45 UTC
Labels: enhancement, clickhouse, P0
