### ISSUE TITLE
Thanks for your effort but it’s really hard to use

### ISSUE THREAD

**Issue by SaihholdChiu** [PostHog/posthog#19368] opened 2023-12-15 18:15 UTC
the Session play is very useful, but custom insight is just too difficult to use, it cost me few hours to understand how to  get a number about how many new registered users per day, however the number was wrong , it was different from my database, I think the problem is time zone, even I have already set time zone but it always shows UTC, I’m about to give it up. thanks anyway

**Comment by pauldambra** [comment] 2023-12-15 18:20
Hey @SaihholdChiu this feels more like you're looking to get support than reporting an issue. So you're better off using the in-app support box at https://app.posthog.com/insights/reEGgMjt#panel=settings%3Asupport%3Aanalytics

Sometimes people see a difference between analytics and their internal records because of ad-blockers blocking data getting to PostHog. You can read more here https://posthog.com/docs/advanced/proxy

I'll close this issue, but do let us know in the support form what insight you're struggling with and whether the data is higher or lower than expected (or whatever else the issue is)

Thanks

**Closed by pauldambra** 2023-12-15 18:20 UTC
Labels: performance
