### ISSUE TITLE
Bug Report: Legend / Chart label mismatch, `POST` vs. `GET`

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#23028] opened 2024-06-17 18:10 UTC
## Bug description

On a Trends insight, the label for the value for the series B column (as displayed in details when hovering over a point on the chart) shows "`POST`" endpoints, but the label on the legend shows it as `GET` endpoints.

## How to reproduce

Example insight:
https://us.posthog.com/project/66696/insights/VaQO0nDg

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/13614

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01902759-e910-7c42-92fd-46ac7ca82bec?t=101 
Admin: http://go/adminOrgUS/01870a20-8a88-0000-b9fc-554df5ff9631 (Project: 66696)
Sentry: http://go/sentryUS/66696
```

**Comment by webjunkie** [comment] 2024-07-11 07:55
Cannot reproduce. Closing for now.

**Closed by webjunkie** 2024-07-11 07:55 UTC
Labels: bug, team/product-analytics, feature/insights
