### ISSUE TITLE
Insight timeframe not saving to dashboard with Custom timeframe selected

### ISSUE THREAD

**Issue by svetlichny** [PostHog/posthog#5323] opened 2021-07-26 07:34 UTC
## Bug description

When there's a dashboard with Custom timeframe selected, the insights that are added to that dashboard are defaulted to 7 days, and after editing a particular insight and setting it to a different timeframe, that change does not persist. No errors are produced on client or server side after updating such an insight. Unlike timeframe, hourly/daily settings and filter settings still do persist.

Thus, it's impossible to create on a single dashboard several insights with non-similar, or even non-default timeframes. Up to v1.24 it was still possible to add insights with different timeframes to a single dashboard. The insights and dashboards created months ago still function like that. However, new dashboards and insights behave like described above.

## Expected behavior

It should be possible to mix insights with different timeframes on a single dashboard with Custom timeframe selected.

## How to reproduce

1. Create new dashboard, set its timeframe to _Custom_.
2. Click "Add graph", the new insight defaults to _daily / 7 days_, don't change anything and save it.
3. Return to the dashboard, click on the newly added insight.
4. Change timeframe to any other, save graph and update it at that dashboard.
5. Return to the dashboard, the timeframe setting is not saved.
6. Same happens if you add new graph and change its timeframe settings before adding it to a dashboard.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.26.0

## Additional context

None.

**Comment by macobo** [comment] 2021-07-30 07:52
cc @paolodamico - worth food for thought re dashboards

**Comment by paolodamico** [comment] 2021-07-30 22:29
Thanks for reporting @svetlichny, indeed an important problem, we'll take a look

**Comment by liyiy** [comment] 2021-08-06 20:21
Duplicate of #5358 I think

**Comment by paolodamico** [comment] 2021-11-25 21:35
Will be addressed by #6712

**Closed by paolodamico** 2021-11-25 21:35 UTC
Labels: bug, dashboards, P1, team-core-experience
