### ISSUE TITLE
User Geolocation

### ISSUE THREAD

**Issue by awang** [PostHog/posthog#2148] opened 2020-10-30 19:28 UTC
## Describe the solution you'd like
It would be great to be able to get the geolocation of each user.  Even better, if you could search for users and sessions that are within a certain range of a specific city! (since you may want to search by metro)

## Describe alternatives you've considered
Enriching the data manually

**Comment by timgl** [comment] 2020-10-30 19:34
Duplicate of #191 (ouch), however it genuinely is around the corner with #1896, so you should have this shortly!

**Closed by timgl** 2020-10-30 19:34 UTC
Labels: enhancement

**Comment by awang** [comment] 2020-10-30 19:36
doh, sorry about that!  i searched for "geolocation" in a few places, but didn't do as careful of a search for "location".

**Comment by timgl** [comment] 2020-10-30 19:37
No worries, definitely still appreciate seeing these as it gives us an idea of what people want :)
