### ISSUE TITLE
Customizable Tables

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1779] opened 2020-09-30 17:29 UTC
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

Add aspects of customization to tables, so I can select the rows and columns that make most sense to me without having the table be auto-generated as the only option

## Describe alternatives you've considered

Leave as is. 

## Additional context

User feedback

**Comment by timgl** [comment] 2020-09-30 17:34
Duplicate of #1534 but will nudge them again

**Closed by timgl** 2020-09-30 17:34 UTC
Labels: enhancement
