### ISSUE TITLE
Metrics and events alerting

### ISSUE THREAD

**Issue by shvatsky** [PostHog/posthog#23176] opened 2024-06-24 05:38 UTC
## Is your feature request related to a problem?

Hi folks! It would be great to have a feature of alerting when some of the metrics are decreasing/increasing or when some event's amount is decreasing or becomes 0.

## Describe the solution you'd like

Feature of alerting in form of email message or similar.

## Additional context

Other systems like Amplitude have this opportunity.

**Comment by jannesblobel** [comment] 2024-06-24 11:55
+10
@shvatsky, thanks for raising this issue. I was just about to suggest it, too. Such a helpful feature.

**Comment by webjunkie** [comment] 2024-07-02 08:41
Closing as duplicate of #14331

**Closed by webjunkie** 2024-07-02 08:41 UTC
Labels: enhancement
