### ISSUE TITLE
Unable to export events as CSV

### ISSUE THREAD

**Issue by ankit7** [PostHog/posthog#8164] opened 2022-01-20 14:38 UTC
Unable to export events as CSV on PostHog cloud. Opens a blank page with attached error on console.  
![image](https://user-images.githubusercontent.com/2109547/150359573-ce4f16d6-b841-4330-b838-f2965a450b71.png)

**Comment by timgl** [comment] 2022-01-21 14:28
@ankit7 Try removing `&orderBy=%5B"-timestamp"%5D` in the URL. Duplicate of #8051

**Closed by timgl** 2022-01-21 14:28 UTC
Labels: bug
