### ISSUE TITLE
Annotations page doesn't refresh on adding a new annotation

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#4277] opened 2021-05-10 10:06 UTC
## Bug description

* Go to annotations page
* Click Create annotation
* Create new annotation
* The annotations page doesn't update, so you're not sure if it saved unless you refresh
* (On refreshing it appears)

<img width="1457" alt="Screenshot 2021-05-10 at 11 04 39" src="https://user-images.githubusercontent.com/47497682/117642708-84afaa80-b17f-11eb-9531-cedf244c69c6.png">

## Expected behavior

* Annotations page should update the list of annotations on saving a new annotation

**Comment by alexkim205** [comment] 2021-06-01 23:41
### Root Cause

This happens because we call [`loadAnnotations`](https://github.com/alexkim205/posthog/blob/634b313602c0528a2a21641e688f366deacdaabd/frontend/src/scenes/annotations/logic.js#L10-L10) too quickly after [creating the global annotation](https://github.com/alexkim205/posthog/blob/634b313602c0528a2a21641e688f366deacdaabd/frontend/src/models/annotationsModel.js#L52-L52). Fix incoming!

**Comment by alexkim205** [comment] 2021-06-04 17:35
Closed by #4564

**Closed** 2021-06-04 17:35 UTC
Labels: UI/UX, bug, core-experience, good first issue
