### ISSUE TITLE
Cannot edit trend series label with formula

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#12039] opened 2022-09-29 20:48 UTC
## Bug description

*Please describe.*  
The edit button doesn't work if there's a formula applied

*If this affects the front-end, screenshots would be of great help.*  
<img width="584" alt="Screen Shot 2022-09-29 at 4 46 51 PM" src="https://user-images.githubusercontent.com/13127476/193138698-c05b084e-449c-4746-8f82-51f22e2f57ca.png">

## How to reproduce

1. Go to trends 
2. Create an insight with formula
3. Try to rename the insight on the table

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

## Additional context
Seems possibly tricky as we're not saving the formula as a discrete filter payload

**Comment by mariusandra** [comment] 2022-10-01 15:19
Seems to be a duplicate of https://github.com/PostHog/posthog/issues/9478 ... which got listed in the next sprint's bug list

**Closed by mariusandra** 2022-10-01 15:19 UTC
Labels: bug
