### ISSUE TITLE
New chart tooltip persists when chart unmounts

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4826] opened 2021-06-21 13:16 UTC
## Bug description

I left the browser window to persist the tooltip

![2021-06-21 15 13 42](https://user-images.githubusercontent.com/53387/122767873-5f947880-d2a3-11eb-8349-f973557f14c4.gif)

## Expected behavior

It goes poof! 💨 

## How to reproduce

1. Get the new tooltip
2. Move the mouse out of the browser window
3. Move back in outside of the graph,
4. Change the page
5. See the tooltip still there

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by paolodamico** [comment] 2021-07-27 02:01
Duplicate of #5061

**Closed by paolodamico** 2021-07-27 02:01 UTC
Labels: UI/UX
