### ISSUE TITLE
In full-screen view i am not able to change playback speed.

### ISSUE THREAD

**Issue by MadhabaPatra** [PostHog/posthog#18788] opened 2023-11-21 17:30 UTC
<img width="304" alt="image" src="https://github.com/PostHog/posthog/assets/42464927/a746f8e3-c89e-43c9-b8b5-ef4a122509e9">

In PostHug [session reply ](https://app.posthog.com/replay) , In full-screen mode, I am not able to change payback speed. To change speed i have to switch to original screen mode.

**Comment by pauldambra** [comment] 2023-11-22 09:11
Hey @MadhabaPatra this is a duplicate of https://github.com/PostHog/posthog/issues/15905 - but thanks for reporting it nonetheless

It is something we want to address but queued behind other work - PRs welcome (although it's probably a little tricky as a change)

**Closed by pauldambra** 2023-11-22 09:11 UTC
Labels: bug
