### ISSUE TITLE
Frontend tech debt

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#10471] opened 2022-06-24 07:36 UTC
Just making a list...

- [ ] remove Provider tags
- [x] upgrade to react 18 (done via https://github.com/PostHog/posthog/pull/17731).
- [x] upgrade to node 18 (done via https://github.com/PostHog/posthog/pull/12650).
- [x] upgrade all logic to kea 3 format via the codemod (done via https://github.com/PostHog/posthog/pull/18232)
- [x] upgrade to pnpm (maybe? [looks promising](https://blog.logrocket.com/javascript-package-managers-compared/) to me) or yarn 3
- [ ] start using workspaces
- [x] upgrade Storybook (done via https://github.com/PostHog/posthog/pull/18113)
- [ ] use ESBuild for Storybook
- [ ] stop using Webpack completely
- [x] fix videos in cypress
- [ ] move lemon ui to their own package folder
- [x] refactor `.LemonLinkButton` class out in favor of Lemon UI components

Longer term goals
- [ ] get rid of custom css and move to components and util classes - https://github.com/PostHog/posthog/issues/16826
- [ ] get rid of antd from the project, abstract via lemon components - https://github.com/PostHog/posthog/issues/16827
- [ ] get rid of antd from lemon-ui's dependency tree

Feel free to add things
- [x] upgrade to webpack v5 (until fully removing webpack) - https://github.com/PostHog/posthog/pull/16648
- [x] update `monaco-editor`  - at least 0.25 is required to satisfy peer requirements for `@monaco-editor/react`
- [x] fix `Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
- [ ] https://github.com/PostHog/posthog/issues/16828
- [x] typescript to v4.9.4

**Comment by kappa90** [comment] 2022-06-28 10:56
@mariusandra I can help with the migration to Vite, would make everything insanely faster.

It is now also supported in Storybook: https://storybook.js.org/blog/storybook-for-vite/

**Comment by mariusandra** [comment] 2022-06-28 11:39
@kappa90 feel free if you feel like storybook is slowing you down. However know that you'll be in for a few annoyances due to our setup:
- there might be issues regarding antd, import paths, less
- the way the toolbar shares styles and renders itself inside a shadow root is very bespoke
- not every tool is happy with the way we alias paths

We (well, mostly me) built a dev server and wrapper around `esbuild` (see `frontend/*.mjs`), which was kind of straightforward, but our custom setup required some workarounds. Feel free to poke around with that. 

I wouldn't mind if we'd eventually be on one platform and one config system, be it `vite` or something else. As long as development reloads stay about as fast as they are, I'm happy to change anything here :).

**Comment by mariusandra** [comment] 2022-06-28 11:40
Basically, go for it if you want, but know it won't likely be a quick thing 😅

**Comment by thmsobrmlr** [comment] 2022-12-09 09:16
- [ ] upgrade to webpack v5 (until fully removing webpack)
- [ ] update `monaco-editor`  - at least 0.25 is required to satisfy peer requirements for `@monaco-editor/react`
- [ ] fix `Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`

**Comment by mariusandra** [comment] 2022-12-09 11:30
Regarding monaco: 
- I've noticed that we load it from a CDN, even though it should also be bundled in. We should make sure that's not happening
- On some pages we use a white Monaco editor (all new query stuff), on some we use a dark skin (app/plugin source editor). What would happen if we used both? What if you go from one to the other?
- Do we fully reset code completion when using a different editor? Should we? E.g. does the "plugin json" editor expect  the data exploration query schema after you loaded the data exploration editor first?

**Comment by guidoiaquinti** [comment] 2022-12-12 14:16
Adding a note related to the Node.js 18 upgrade: we [had to add](https://github.com/PostHog/posthog/pull/12650#discussion_r1045827412) the `openssl-legacy-provider` option in order to make things working. Once some dependency tech debt will be paid, we should remove that flag.

**Comment by thmsobrmlr** [comment] 2022-12-15 08:59
Adding migration to Chart.js v4: https://www.chartjs.org/docs/latest/migration/v4-migration.html

**Comment by Arun-chaitanya** [comment] 2023-08-21 18:21
@thmsobrmlr @mariusandra @Twixes  I was trying to convert the front end to Vite. I was able to convert many things compatible with Vite. But I am facing one issue one it comes to userLogic even though I haven't kept it the same as in the current repo. I am getting the following error. I would be grateful if some body could take a look at this.
Vite Repo Link: [https://github.com/Arun-chaitanya/posthog-vite](https://github.com/Arun-chaitanya/posthog-vite)
To start the vite server: `npm run dev`
<img width="840" alt="Screenshot 2023-08-21 at 11 49 33 PM" src="https://github.com/PostHog/posthog/assets/44457256/ef5ee031-40e2-419f-9293-560fd039c413">

**Comment by mariusandra** [comment] 2023-08-21 19:01
Hey, a hunch tells me that if you change these lines:

```ts
    connect({
        values: [preflightLogic, ['preflight']],
    }),
```
to these:
```ts
    connect(() => ({
        values: [preflightLogic, ['preflight']],
    })),
```

It'll work. Something about the load order of the files in vite vs esbuild being different likely means `userLogic` and `preflightLogic` end up imported in a different order. Moving the `connect` call's props to a inline function makes kea evaluate the reference to `preflightLogic` at runtime, not at script load time. It'll likely be resolved by then.

**Comment by Arun-chaitanya** [comment] 2023-08-21 19:22
@mariusandra got it. I will try this and keep you guys in the loop about the progress. Thanks :)

**Comment by Arun-chaitanya** [comment] 2023-10-23 12:07
@mariusandra @thmsobrmlr I am successfully able to replace esbuild with vite 
Successfully achieved tasks are:
1) No typescript errors
2) Hot reload in the dev environment with Vite
3) Prod build with Vite.

However, I can see in webpack.config.js that we are building index.html as well as layout.html. As per my understanding, index.html is the entry file for the app.posthog.com, But I am not able to understand what is layout.html about. 
Can you please explain a brief about layout.html, what is its role and functionality?

That being said you can track my progress at https://github.com/Arun-chaitanya/posthog-vite

**Comment by mariusandra** [comment] 2023-10-24 10:01
Hey @Arun-chaitanya , that file is used for most regular [python/django templates](https://github.com/PostHog/posthog/tree/master/posthog/templates).

**Comment by daibhin** [comment] 2023-10-27 10:22
I didn't realise we had an issue tracking our frontend improvements. I've been doing a lot in the background to get React 18 over the line:
[x] Upgrade Weback to v5 - https://github.com/PostHog/posthog/pull/16648
[x] Upgrade `react-virtualized` to support React 18 - https://github.com/PostHog/posthog/pull/16890
[x] Upgrade `react-resizeable` to support React 18 - https://github.com/PostHog/posthog/pull/16891
[x] Remove `react-input-autosize` because it does not support React 18 - https://github.com/PostHog/posthog/pull/16894
[x] Replace `react-json-view` with a fork that supports React 18 - https://github.com/PostHog/posthog/pull/17713
[x] Replace unmaintained package `react-textfit` because it does not support React 18 with an in house implementation - https://github.com/PostHog/posthog/pull/17720

**Comment by daibhin** [comment] 2023-10-27 10:27
Also big props to @mariusandra for the massive help upgrading Storybook to v7 in https://github.com/PostHog/posthog/pull/17078 which was required by React 18

**Comment by arunfancraze** [comment] 2023-11-12 18:54
[Running into error while trying to run DEBUG=1 ./bin/migrate](https://posthog.com/questions/running-into-error-while-trying-to-run-debug-1-bin-migrate)
Hi I tried followed all the above steps and was successfully able to complete all of them. But when I try to run DEBUG=1 ./bin/migrate, I am getting following error. I have pasted the error in Notion. [https://checker-drug-d0e.notion.site/Posthog-Error-dd4d1cd6db2c4fd3bcbebd1b9b9d0820](https://posthog.com/handbook/engineering/developing-locally) I copy-pasted the error in ChatGPT and Bard and the answer from both was that This error indicates that the Django application is trying to connect to a PostgreSQL database using a role (user) named "posthog," but that role doesn't exist in your PostgreSQL database.

**Comment by thmsobrmlr** [comment] 2023-11-12 19:09
Hey @Arun-chaitanya, might be best to move this to a separate issue, as it's a bit off topic here. Nevertheless, how are you running Docker on the M1? Do you use Docker Desktop / OrbStack / something else? What do the logs for the container say= I could imagine that this is caused by a separate Postgres instance running via Postgres.app, Homebrew, or something else.

**Comment by arunfancraze** [comment] 2023-11-12 19:46
@thmsobrmlr deleted here and mentioned it in https://github.com/PostHog/posthog/issues/18561

**Comment by Twixes** [comment] 2024-04-22 12:59
I think we've done enough of this, that we probably will only the rest when the need becomes strong it. (There are also some edge cases, e.g. Storybook requires as to use either Webpack or Vite for builds anyway, so we won't be moving to 100% ESBuild. And Ant removal is progressing in between other things.)

**Closed by Twixes** 2024-04-22 12:59 UTC
