### ISSUE TITLE
White screen when viewing screen recording

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5574] opened 2021-08-12 19:21 UTC
## Bug description

White screen of death when going to some of our session recording pages.

Example - https://app.posthog.com/sessions?sessionRecordingId=17b26c368e50-0bc9493cd9f73c-7c6c065a-1fa400-17b26c368e629b&filters=%5B%5D

<img width="464" alt="Screen Shot 2021-08-12 at 12 21 20 PM" src="https://user-images.githubusercontent.com/13460330/129256192-6d6aded7-19a1-4c34-82f2-664f067ab9c7.png">

## Expected behavior

No white screen of death

## How to reproduce

1. Navigate to above screen recording
2. App crashes 
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

I don't believe this was caught by sentry

**Comment by paolodamico** [comment] 2021-09-16 07:20
Duplicate of #3154

**Closed by paolodamico** 2021-09-16 07:20 UTC
Labels: bug, session recording, P0, team-core-experience
