### ISSUE TITLE
Paths fail with invalid URLs

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2717] opened 2020-12-09 15:45 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Overriding `$current_url` on pageviews to non-URL values leads the Paths page to crash.  I believe I remember this working in the past.

## Expected behavior

Paths should work for non URL values (e.g. screen names on an app)

## How to reproduce

1. Send pageview events with `$current_url` set to some arbitrary string
2. Navigate to the paths page
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by EDsCODE** [comment] 2021-02-03 22:52
#3168 might have solved this. I'm not sure if they're the same cause but the URL was malformed and throwing an uncaught exception when the URL object was created

**Comment by macobo** [comment] 2021-02-08 14:17
I couldn't reproduce this after #3168 - can close this?

**Closed** 2021-02-08 14:19 UTC
Labels: bug
