### ISSUE TITLE
"Update and run" source code of an insight doesn't work

### ISSUE THREAD

**Issue by lksrpp** [PostHog/posthog#21563] opened 2024-04-16 09:58 UTC
## Bug description

* I wanted to copy some insight information from one project to another project by using the source code view
* I realised that the "update and run" button doesn't do anything
* The same problem persists without copying over code; if I change an existing insight's source code it is not updated
* If this isn't fixed, I would have to create a lot of insights by hand again.

## How to reproduce

1. Open an insight
2. Select "view source code"
3. Change anything in the source code
4. Click: "Update and run"
5. See that nothing happens.

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ee632-2bd6-733c-87c4-2ef7e19c3043?t=2418 
Admin: http://go/adminOrgEU/018bfb3f-1be1-0000-eaa4-606a4fc275f5 (Project: 13779)
Sentry: http://go/sentryEU/13779
```

**Comment by MarconLP** [comment] 2024-04-17 05:54
duplicate of https://github.com/PostHog/posthog/issues/17839

**Closed by MarconLP** 2024-04-17 05:54 UTC
Labels: bug
