### ISSUE TITLE
Automatically make actions for custom events

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2077] opened 2020-10-28 16:08 UTC
I've had a couple of calls where users seemed to confuse custom events and actions.

I know we're working to improve our actions UX, but I thought it could be useful to make actions from custom events by default. 

We keep saying actions are a way to sort through events you "care about" and I'd expect people to care about the events they themselves create. This can also help to populate the actions page and get people to use it more.

@paolodamico thoughts?

**Comment by Twixes** [comment] 2021-04-29 12:02
I think this is a duplicate of #192.

**Closed by Twixes** 2021-04-29 12:02 UTC
Labels: enhancement
