### ISSUE TITLE
Can't breakdown more than one property

### ISSUE THREAD

**Issue by rfguri** [PostHog/posthog#13464] opened 2022-12-22 11:26 UTC
We want to breakdown by multiple properties set on a custom event, but UI only allows one to be set.

**Comment by neilkakkar** [comment] 2022-12-22 11:32
Hey @rfguri , this request makes sense.

I'll close it as a duplicate of https://github.com/PostHog/posthog/issues/938 though

**Closed by neilkakkar** 2022-12-22 11:32 UTC
Labels: bug

**Comment by rfguri** [comment] 2022-12-22 12:27
Do you know an approximate ETA? I've seen the [#938](https://github.com/PostHog/posthog/issues/938) has been open since Nov

**Comment by neilkakkar** [comment] 2022-12-22 12:39
As far as I know, at best Q2 2023

**Comment by mariusandra** [comment] 2022-12-22 14:30
There is a [draft pr](https://github.com/PostHog/posthog/pull/13264) out that adds this support via hogql expressions, and should land in Q1
