### ISSUE TITLE
Dashboard Always Loading

### ISSUE THREAD

**Issue by ourcaldo** [PostHog/posthog#22272] opened 2024-05-13 10:26 UTC
### Bug Description

Hi guys,

I tried to install Posthog in Google Cloud Console using ubuntu 20.04. When it's done, I try to login to my dashboard, but it's always loading. When I try to open debug console with google chrome, it's looks like this.

Is there any solution for this issue?

<img width="960" alt="Screenshoot_1513_100524" src="https://github.com/PostHog/posthog/assets/85465492/b759a90e-ced7-4f15-b3a6-36d9fcf2b464">

### Debug info

```shell
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: latest
```

**Comment by jgoclawski** [comment] 2024-05-14 16:46
I think this is a duplicate of https://github.com/PostHog/posthog/issues/22198

**Comment by Twixes** [comment] 2024-05-20 11:19
Closing as duplicate, please see the other issue!

**Closed by Twixes** 2024-05-20 11:19 UTC
Labels: bug
