### ISSUE TITLE
Set `is_identified` on person when person is identified using `$set`

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3784] opened 2021-03-29 14:46 UTC
## Bug description

We support setting user properties through `$set` on events (see _Setting user properties via an event_ on [Javascript integration](https://posthog.com/docs/integrations/js-integration)). The problem is that if you identify a user using this method (e.g. setting an email address), we don't update the person's `is_identified` property (see [relevant source code](https://github.com/PostHog/plugin-server/blob/b0b1905b2f3835924e4b6bc852de83ab0588b73e/src/worker/ingestion/process-event.ts#L173)) and therefore it is incorrectly shown as anonymous on the app.

## Expected behavior

- Mark a user's `is_identified = True` if they set up identification properties (e.g. `email`, `name`, `username`, ...), no matter how these properties are set?
- Maybe the above is not the best approach as it could lead down a rabbit hole of edge cases on how to consider a user identified. In which case it's a documentation issue, we would need to make very clear that you need to call `posthog.identify` when identifying a user.

## How to reproduce

1. Set a user's email using `$set`
2. See user's property in the person page but still showing up as anonymous.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

## Additional context
Reported by a user who is identifying users via `$set`.

**Comment by mariusandra** [comment] 2021-03-29 18:43
You can call `.identify` with `$set` and `$set_once` (see "Identifying Users" in [Javascript integration](https://posthog.com/docs/integrations/js-integration)). So the question is quite simple: if you want your user identified, call `.identify`. if not, use `set` or `set_once` directly :)

**Comment by kpthatsme** [comment] 2021-03-30 18:13
@paolodamico I agree with the confusion around this and like your suggestion of automatically identifying any users that have an identity property set. 

I think it's confusing that we can send special identification properties (e.g. email) that show up in the person tab but then still show the user as anonymous. I also think the expected behavior based on other products would be for this user to show as identified (and merged with any others) if an identifier is set.

**Comment by yakkomajuri** [comment] 2021-03-31 09:15
I think this has been exacerbated by the new persons page approach to it - so we could consider a different UI approach. 

Currently we get stuff like `Anonymous user l.com` and `Anonymous user thog`

**Comment by paolodamico** [comment] 2021-04-02 01:13
My R$0.02 based on how this has evolved since #3848. I think it's actually a good thing that the new UI is bringing this issue up. Makes it very clear if you're missing something in your integration. Otherwise, this could lead to wrong metrics where you rely on the `is_identified` property. I suggest we keep this issue up for improving both the in product docs (I'm tackling this) and the general docs, to clarify that you should call `$identify` if you want to have identified users.

**Comment by tiina303** [comment] 2021-09-08 22:15
Somewhat related to this (specifically the idea of if identification properties are set the user should be identified), when someone does a merge starting from an unidentified user they end up with "Unidentified <email>". I suspect this happens because like the Note says in the popup that upon conflicts the person I was on values take precedence (starting the merge from an identified person ends up identified).

**Closed** 2023-02-06 14:07 UTC
Labels: bug, feature/persons
