### ISSUE TITLE
Filter on nested properties

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5863] opened 2021-09-08 20:16 UTC
## Is your feature request related to a problem?
Some of our custom events attach nested objects as a property (e.g. line item, sales order, etc.). We sometimes want to filter on nested properties, but can't do that in the UI other than through `contains` or a regex.

While the following is a bit contrived to protect user data, I might want to filter on `event_metadata.subscriptionTier`: 
<img width="569" alt="Screen Shot 2021-09-08 at 2 11 32 PM" src="https://user-images.githubusercontent.com/74929925/132578901-41212d64-d6ad-4808-b5a2-0e395229e17f.png">

## Describe the solution you'd like
A way to specify nested properties that we'd like to filter on. E.g. `event_metadata.subscriptionTier CONTAINS 'basic'`

## Describe alternatives you've considered
Using `contains` or a regex on the object's JSON, which works but is clunky

**Comment by timgl** [comment] 2021-09-10 15:31
Hey @dknowles-vsk, I'm closing this as a duplicate of #4593 but thanks for raising! In the mean time, you should have a look at the property-flattener plugin: https://posthog.com/plugins/property-flattener

**Closed by timgl** 2021-09-10 15:32 UTC
Labels: enhancement, analytics-filters
