### ISSUE TITLE
Clicking on Filter in Session show empty filters

### ISSUE THREAD

**Issue by razorinc** [PostHog/posthog#3260] opened 2021-02-09 11:52 UTC
## Bug description

When in Sessions

![Screenshot from 2021-02-09 12-38-58](https://user-images.githubusercontent.com/260005/107359176-a774e900-6ad4-11eb-8281-b459a8e496fc.png)
or in People -> Cohort

![Screenshot from 2021-02-08 20-22-33](https://user-images.githubusercontent.com/260005/107359438-f6228300-6ad4-11eb-87d5-a8b0c8145400.png)

pressing the menu Property offer me a no data message.

## Expected behavior

When I open FIlters, and then Property I expect to see the same properties I see in Insights.

## How to reproduce

1. Open Sessions
2. Press on Filters
3. Read the No Data

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog, version/commit: Installed through Helm from your helm chart version 1.4.4 

## Additional context

I'm available for further investigations, but I see no errors in the javascript console

**Comment by alexkim205** [comment] 2021-06-02 18:48
Hey @razorinc! Our Filtering UX has changed quite a bit since 1.4.4 (current [v.1.4.16](https://github.com/PostHog/charts/releases/tag/posthog-1.4.16)) and I'm unable to reproduce the no data bug above (see screenshots below). This could mean that the bug's been fixed already (which would be great!) or we're just unable to reproduce your use case.

What sessions and cohort filters look like in v.1.4.16:

<img width="840" alt="Screen Shot 2021-06-02 at 10 47 51 AM" src="https://user-images.githubusercontent.com/13460330/120535627-16ce5b80-c398-11eb-9923-51ef5e250cfc.png">
<img width="969" alt="Screen Shot 2021-06-02 at 10 56 11 AM" src="https://user-images.githubusercontent.com/13460330/120535717-29489500-c398-11eb-819d-38966df65c3b.png">

In the meantime:

1. Could you post a screenshot of what you expect the filter to look like/what it looks like in the insights tab? 
2. Can you [upgrade](https://posthog.com/docs/deployment/deploy-kubernetes#updating-your-posthog) to the latest version of PostHog to see you run into the same problem?

Thanks!

**Comment by mariusandra** [comment] 2021-06-04 12:22
I think this got fixed somewhere down the line (this issue is up from February, we're in June). Thus closing. Please feel free to repoen @razorinc if it's still happening.

**Closed by mariusandra** 2021-06-04 12:22 UTC
Labels: P0, bug
