### ISSUE TITLE
Searching for a person by identifier returns 500

### ISSUE THREAD

**Issue by u-ashish** [PostHog/posthog#9890] opened 2022-05-20 18:59 UTC
## In what situation are you experiencing subpar performance?

Searching for a person in `Persons & Groups` by identifier returns 500. This has been happening for a couple weeks now...

## How to reproduce

1. Go to `Persons & Groups`
2. Search for person by identifier
3. Wait for a while. It errors out. Network tab shows 500 response.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by neilkakkar** [comment] 2022-05-23 09:51
Thanks for pointing this out, @u-ashish , sounds like a duplicate of https://github.com/PostHog/posthog/issues/8660

**Closed by neilkakkar** 2022-05-23 09:51 UTC
Labels: performance

**Comment by u-ashish** [comment] 2022-05-23 18:13
> Thanks for pointing this out, @u-ashish , sounds like a duplicate of #8660

Oops yeah sorry I missed it!
