### ISSUE TITLE
Key retention table is broken

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2802] opened 2020-12-16 23:56 UTC
## Bug description

Seems the retention table broke down with a recent commit (currently happening on Cloud version). Seems to only be happening when certain filters are applied.

Frontend issue: https://sentry.io/organizations/posthog/issues/2096748405/?project=1899813
Underlying backend issue: https://sentry.io/organizations/posthog/issues/2096376926/?project=1899813

## Expected behavior

Retention table should load normally.
<img width="1431" alt="Screenshot 2020-12-16 at 5 54 05 PM" src="https://user-images.githubusercontent.com/5864173/102420456-ccaf1480-3fc7-11eb-8b4b-fae7ae48b932.png">

## How to reproduce

1. Open [this link](https://app.posthog.com/insights?startEntity=%7B%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22user%20signed%20up%22%7D%5D%2C%22new_entity%22%3A%5B%5D%7D&returningEntity=%7B%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%7D%5D%7D&retentionType=retention_first_time&selectedDate=2020-12-06%2006%3A00&period=w&properties=%5B%7B%22key%22%3A%22id%22%2C%22value%22%3A71%2C%22type%22%3A%22cohort%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22www.posthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22https%3A%2F%2Fposthog.com%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22localhost%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%22127.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%2C%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%220.0.0.1%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22event%22%7D%5D&insight=RETENTION&display=ActionsTable)

## Environment

- [X] PostHog Cloud

## Additional context

CC @EDsCODE

**Comment by macobo** [comment] 2020-12-18 10:36
This was fixed, duplicate of #2813

**Closed by macobo** 2020-12-18 10:36 UTC
Labels: bug

**Comment by paolodamico** [comment] 2021-01-03 21:02
For future reference, I think it's worth making sure we make these changes backwards-compatible, as if you have bookmarks or stuff like that, it'll break the links without you knowing why.
