### ISSUE TITLE
Rolling Retention

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2220] opened 2020-11-04 13:48 UTC
## Is your feature request related to a problem?

*Please describe.*
Provide retention graph for rolled over users not just users retaining on a specific day

## Describe the solution you'd like
The graph should backfill so if there's a 40% return rate on timebox 2 it means 40% returned that day or any day after that. Right now we're just showing the percentage of people returning exactly on that day

**Comment by paolodamico** [comment] 2020-11-05 07:12
Context for someone else reading this. This is also called unbounded retention, in which a user is counted as retained up until the last period they were retained. This can serve for some interesting analysis, however it doesn't seem like it should be used as our main metric (to gauge PMF) because we lose the data points of when users dropped, like if users did not return on periods 2 & 3 but returned on 4. It's quite important to understand this (it for instance can indicate that the problem we're solving has a different frequency from what we expected). It can also lead to some noisy edge cases, for example consider a user that signs up on period 0 and returns on period 10, and we don't see them again, we'll count them as dropped until period 10, but they weren't really retained on periods 1 through 9.

For what is worth, I would assign a lower priority to this, particularly over #2219 & #1936.

**Comment by joebudi** [comment] 2022-04-26 14:06
Just leaving a note to say I am looking forward to this specific feature and keep up the great work!

**Comment by isAdrisal** [comment] 2024-08-23 11:25
Dupe of #23661

**Comment by annaszell** [comment] 2024-09-06 18:05
Fixed in: https://github.com/PostHog/posthog/pull/24240

**Closed** 2024-09-06 18:04 UTC
Labels: enhancement, feature/retention, team/product-analytics
