### ISSUE TITLE
Cannot update funnel insight via JSON source.

### ISSUE THREAD

**Issue by oconn** [PostHog/posthog#21731] opened 2024-04-22 16:40 UTC
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. Create a funnel report 
2. Enable `View Source` setting
3. Make changes and save

## Additional context

Fails to apply changes to JSON source. I've created some funnels in a dev env that I'd rather not have to manually create in the prod env.

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f0651-61c6-7254-8df3-a0398726b4b9?t=5859 (at https://us.posthog.com/project/29524/insights/new#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/0188e3fe-bd0c-0000-3261-112611085fe5 (Project: 29524)
Sentry: http://go/sentryUS/29524
```

**Comment by MarconLP** [comment] 2024-04-22 20:55
duplicate of #17839

**Closed by MarconLP** 2024-04-22 20:55 UTC
Labels: bug
