### ISSUE TITLE
Filtering out test accounts not fully working?

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#3668] opened 2021-03-16 16:03 UTC
## Bug description

I created a funnel with `email contains @posthog.com` (made sure it was the user prop)

Then I turned on our filter for test accounts (`email does not contain @posthog.com`) and still got users.

## Expected behavior

Filter should work.

## How to reproduce

1. Create a funnel and add a filter `email contains @posthog.com` 
2. Turn on `filter out test accounts`
3. There will still be users on the funnel

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by timgl** [comment] 2021-03-18 13:36
Dumping thoughts here as i have to do something else

```
SELECT pid.person_id as id, (select JSONExtractRaw(person.properties, 'email') from person where person.id=id limit 1), groupArray(events.distinct_id)
          FROM events
          JOIN (
                SELECT person_id,
                       distinct_id
                  FROM person_distinct_id
                 WHERE team_id = 2
               ) as pid
            ON pid.distinct_id = events.distinct_id
         WHERE team_id = 2

           AND NOT has(['localhost:8000', 'localhost:5000', '127.0.0.1:8000', '127.0.0.1:3000'], trim(BOTH '"' FROM JSONExtractRaw(events.properties, '$host')))
           AND team_id = 2
           AND events.distinct_id IN (
                SELECT distinct_id
                  FROM person_distinct_id
                 WHERE person_id IN (
                        SELECT id
                          FROM person
                         WHERE team_id = 2
                           AND NOT (trim(BOTH '"' FROM JSONExtractRaw(properties, 'email')) LIKE '%@posthog.com%')
                       )
                   AND team_id = 2
               )
           and events.timestamp >= '2020-12-18 00:00:00'
           and events.timestamp <= '2021-03-18 23:59:59'
           AND event IN ['$pageview', 'insight viewed', 'insight viewed', 'insight viewed']
            AND pid.person_id IN ['a395eaa1-f657-4d79-92d4-a8c358182260',
'968f4ffa-a01b-446d-b1d0-c7929bbbb80f',
'758fce7f-5d78-46b7-9dff-95c707b29ae0',
'48600956-96bf-4edd-acdb-4bc2e01b2b56',
'017844aa-7c76-0000-bf23-3523ca658ec5',
'01784151-14a0-0000-9aec-24cb2cb3bcd0',
'01784150-e8a5-0001-628d-f94ebda8a8bc',
'0178369d-3627-0000-dd17-45de1f2f3243',
'01782366-db2f-0000-6888-a457d33c7233',
'017821d4-2137-0000-1a07-b0ad8a5ff2d5',
'01781ec7-6f79-0000-e5b9-4172d93c762b',
'0177f3ae-f7ec-0001-45e4-6d585e669f2a',
'0177f323-a758-0001-9d0a-383cc917c505',
'0177ee66-b9f5-0000-7cea-0015b47cfaf1',
'0177e116-cc9b-0000-d980-087f5f245d83',
'0177b227-3d19-0000-5c18-985675e0313d',
'0177ad9c-70bc-0000-1edd-80d28a7074ea',
'0177a6bf-6ad4-0000-3003-ed10eb4b52c8',
'017589ed-d162-0000-1a98-8771bc571b34'
]
         GROUP BY pid.person_id;
```

This will still return a bunch of posthog.com emails, but if you switch it around like this:
```
AND events.distinct_id NOT IN (
                SELECT distinct_id
                  FROM person_distinct_id
                 WHERE person_id IN (
                        SELECT id
                          FROM person
                         WHERE team_id = 2
                           AND (trim(BOTH '"' FROM JSONExtractRaw(properties, 'email')) LIKE '%@posthog.com%')
                       )
                   AND team_id = 2
               )
```

it's correct.

**Comment by Twixes** [comment] 2021-08-05 10:41
I can't reproduce this, so I suspect this has been fixed via all the refactoring since this was filed. Do you still see this @yakkomajuri?

**Comment by EDsCODE** [comment] 2021-08-06 16:54
I also just checke on this and it seems fixed. Will close for now

**Closed by EDsCODE** 2021-08-06 16:54 UTC
Labels: bug, P0, analytics-filters
