### ISSUE TITLE
Experiments no code interface

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#17655] opened 2023-09-27 15:33 UTC
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

I want to be able to create an experiment touching as little code as possible.

**Comment by neilkakkar** [comment] 2023-09-27 15:37
Duplicate of https://github.com/PostHog/posthog/issues/16417

**Closed by neilkakkar** 2023-09-27 15:37 UTC
Labels: enhancement, feature/experimentation
