### ISSUE TITLE
Sequence of events as action

### ISSUE THREAD

**Issue by mayeraaa** [PostHog/posthog#20059] opened 2024-01-31 10:22 UTC
It would be helpful if I could set a sequence of events as an action. 
Now in the interface, on the action creation page, the default is OR connection. I would change it to an AND connection. To make action, for example, a sequence of events. This seems like an basic functionality (for our product this case is more common than OR).
Thanks.

**Comment by mariusandra** [comment] 2024-01-31 12:04
Hey @mayeraaa , you can currently do this when creating a cohort, and then use the cohort to filter your events.

**Comment by mayeraaa** [comment] 2024-02-05 07:30
@mariusandra Thanks for the answer. But in this case, can I find out the total number of such actions (multiple events)?

**Comment by mariusandra** [comment] 2024-02-05 09:27
Depends on what you are tracking, how your data is structured, and what results you want to see 😅 

You can filter by cohort, and then under Trends ploy a line to see how many people did the first or last action, or how many times a person did it. The cohort filter should assure that only users who did the steps will show up, and checking for the last step should be conclusive then? But again, depends on your data :)

**Comment by mayeraaa** [comment] 2024-02-16 13:18
I have a very simple task, which occurs quite often (and I think I’m not the only one): I need to count the number of complex events consisting of several sequential actions. Not the number of users who made this sequence (as I understand it, this can be done as a cohort), but the total number of such sequences.
Is this possible now or not?

**Comment by mariusandra** [comment] 2024-02-20 08:13
Well, technically you have the option to write a custom SQL query (with window functions?) over your events, so it is possible today if you know how. 

The simpler option today, which assumes that every _last_ event in this sequence uniquely identifies the completion of the sequence, is to create a cohort for people completing the full sequence, and then count the number of last events.

Another option is to use a funnel, but instead of aggregating by unique users, aggregate over unique sessions. This won't work if there are more than one completed sequence in one session.

**Comment by mayeraaa** [comment] 2024-02-20 08:45
Thanks for the help.
The proposed options, unfortunately, do not completely solve the problem. Even a method with a SQL request. Although a rough estimate can be obtained.
It would be cool if in the future it would be possible to set a sequence of events as an action.

**Comment by Twixes** [comment] 2024-07-11 12:25
I'll close this as a duplicate of #3136, but this is definitely on our radar

**Closed by Twixes** 2024-07-11 12:25 UTC
Labels: enhancement, team/product-analytics

**Comment by mayeraaa** [comment] 2024-07-11 12:34
Great, I'm still really looking forward to this feature.
