### ISSUE TITLE
Group-level analytics

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#3963] opened 2021-04-12 22:52 UTC
## Is your feature request related to a problem?

While we care about user growth and the experience of individual users, we need to have a way to look at organizations as a whole in PostHog.

For example, right now, there isn't a good way in PostHog to grab an 'Active Orgs' number. Likewise, we can't look at the conversion rate of all orgs to ingesting data, since that is keyed to specific users in the org.

## Describe the solution you'd like
I would like to be able to associate groups with users in PostHog.

We can tie users to specific group ids, and any events fired from a user that also has a group ID, these events will get associated with the entire group.

Here is a [good article for this works at other analytics companies](https://help.amplitude.com/hc/en-us/articles/115001765532-Accounts).

## Describe alternatives you've considered
Work arounds in PostHog. I believe all work arounds would include either firing extra events (that don't necessarily belong to a user) or enhance our querying abilities within PostHog to be able to group distinct users by a property, such as Org Id. I think this latter idea is something we'll need to build into PostHog no matter what, but I don't think it's the solution for this group level analysis.

## Additional context
This would open up a ton of value for us as well as our users. Most companies have the notion of groups / teams and this would open up analysis on those entities in a flexible way.

**Comment by paolodamico** [comment] 2021-04-12 22:56
Think this is a duplicate of #2247 but the extra context is certainly super helpful.

**Closed** 2021-04-13 12:34 UTC
Labels: enhancement
