### ISSUE TITLE
Conditional funnel steps

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#6008] opened 2021-09-17 08:52 UTC
## Is your feature request related to a problem?

[From the users slack](https://posthogusers.slack.com/archives/CT7HXDEG3/p1631820111161000?thread_ts=1631257214.101200&cid=CT7HXDEG3): "We have steps in our order flow that is only showed for some specific customers but we still want to track if they dropped on that step."

## Describe the solution you'd like

For example in a funnel:

- "View site" -> "Add to cart" -> "Open cart" -> "Upgrade account" -> "Pay"

... I would like to make the "upgrade account" step optional/conditional/transparent, as only some some users will see it, yet I'd still like to track how many did the step.

## Describe alternatives you've considered

- Create an action "users were shown to upgrade their account"
- Create two funnels, one with and one without a global filter excluding those users

**Comment by Twixes** [comment] 2021-09-17 09:29
Duplicate of #5515 I think.

**Closed by Twixes** 2021-09-17 09:29 UTC
Labels: enhancement, funnels, team-core-analytics
