### ISSUE TITLE
Insights tooltip hangs around for too long

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog#5396] opened 2021-07-30 11:45 UTC
## Bug description

![image](https://user-images.githubusercontent.com/11272509/127648256-701d0ddf-5345-4785-a1cd-17e8daf21ccb.png)

When I go to the the insights and hover over a tooltip, then switch to another page. The tooltip persists and does not go away.

## Expected behavior

The tooltip goes away when my mouse leaves it.

## How to reproduce

1. View an insights graph
2. Hover over a line to get the tooltip
3. Go to the events page

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.27.0

## Additional context

N/A

**Comment by paolodamico** [comment] 2021-07-30 14:18
Duplicate of #5061

**Closed by paolodamico** 2021-07-30 14:18 UTC
Labels: bug
