### ISSUE TITLE
Make use of memory in clickhouse nodes

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5244] opened 2021-07-21 08:17 UTC
## Is your feature request related to a problem?

I was looking at clickhouse memory usage stats in https://metrics.posthog.com/d/eP5hb3rGz/clickhouse-queries?orgId=1&from=now-90d&to=now and noticed clickhouse memory usage never goes above ~25GB. Our boxes have an order of magnitude more available.

Is this a lever for potential speedups? 

## Describe the solution you'd like

From https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings_max_memory_usage

```
max_memory_usage 
The maximum amount of RAM to use for running a query on a single server.

In the default configuration file, the maximum is 10 GB.

The setting does not consider the volume of available memory or the total volume of memory on the machine.
The restriction applies to a single query within a single server.
You can use SHOW PROCESSLIST to see the current memory consumption for each query.
Besides, the peak memory consumption is tracked for each query and written to the log.

Memory usage is not monitored for the states of certain aggregate functions.

Memory usage is not fully tracked for states of the aggregate functions min, max, any, anyLast, argMin, argMax from String and Array arguments.

Memory consumption is also restricted by the parameters max_memory_usage_for_user and max_server_memory_usage.
```

I think we're using the default maximum and could increase this a lot.

## Additional context

It would be nice to have the configuration files under version control and deploy them automatically via an ansible script. We probably have other fine-tuning tools available.

Related: https://github.com/PostHog/posthog/issues/5112

cc @tiina303 and @fuziontech

**Comment by fuziontech** [comment] 2021-07-29 23:47
ClickHouse heavily uses the OS page cache so almost all of the memory on the nodes is utilized. There actually is no other cache internal to ClickHouse. https://clickhouse.tech/docs/en/operations/caches/

We even did a test where we loaded all of the person table into memory and there was no improvement in speed of queries against the fully in memory table. That's the beauty of these OLAP databases is just how well they leverage linux and the filesystem to properly use built in caching mechanisms instead of rebuilding them.

A quick snapshot of just how much memory we are using:
![image](https://user-images.githubusercontent.com/391319/127579475-c4b30cc6-a4aa-462f-93fd-7e1f0cb10222.png)
```
ubuntu@ip-172-31-47-136:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:         382622        4443        5612           1      372565      375214
Swap:             0           0           0
```
Only **5gb** of memory is unused and free right now. **375gb** is available (but used as page cache).

If you want to give this a try yourself copy `person` or `person_distinct_id` table into memory engine backed table and test the speeds. We saw no improvement.

Further reading on how page cache on linux works and how amazing it is:
https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics

BTW this is the same way Postgres speeds up reads as well as an internal version.
https://sites.google.com/site/itmyshare/database-tips-and-examples/postgres/postgresql-buffering

**Comment by macobo** [comment] 2021-07-30 06:37
Good summary!

However, some queries are currently failing due to not enough memory for existing clients, which bumping this setting would help as well.

![image](https://user-images.githubusercontent.com/148820/127611319-d55b32df-efd4-4fbb-a1dc-08eea7c5d90f.png)

https://sentry.io/organizations/posthog/issues/?project=1899813&query=is%3Aunresolved+memory+limit&statsPeriod=14d

**Comment by fuziontech** [comment] 2021-07-30 15:56
Yup! That is definitely true. This is not a performance issue as much as it is a query bugging out issue.

We just want to be careful with this because the more memory we give ClickHouse to complete these queries the less linux will have for the page cache.
![image](https://user-images.githubusercontent.com/391319/127679234-07f801da-74ea-4b65-b598-6f4b50e6ba5e.png)
and these make up only a small fraction of our overall query volume so it's not a huge priority. 

I would be ok raising the limit from 10gb to maybe 12-14gb for testing.

**Comment by fuziontech** [comment] 2021-09-15 18:54
Closing because ClickHouse really does use memory effectively - We can open up separate tickets for reducing errors caused by the working memory available to ClickHouse

**Closed by fuziontech** 2021-09-15 18:54 UTC
Labels: enhancement, infrastructure, clickhouse, performance
