### ISSUE TITLE
Allow use of Path Replacement options in Path fields in Trends (and other non-Paths insights)

### ISSUE THREAD

**Issue by suavesav** [PostHog/posthog#22173] opened 2024-05-08 03:09 UTC
## Is your feature request related to a problem?
I would like to have a better breakdown based on paths. Posthog already supports path cleaning in the Paths Insight...ideally that would be extended whenever a Path field is referenced in an Insight.

## Describe the solution you'd like

Add ability to apply 'Path Cleaning Rules' here.
<img width="484" alt="Screenshot 2024-05-07 at 8 04 26 PM" src="https://github.com/PostHog/posthog/assets/3641655/1ee4f6d6-e078-4587-a610-6b9e458e2ecc">

i.e. support for `pathReplacement=True` in 
```
"breakdownFilter": {
      "breakdown_type": "event",
      "breakdown": "$pathname",
      "breakdown_normalize_url": true
    }
```

## Describe alternatives you've considered
Creating path based Actions for every path I want to track and manually adding each Action as a Series. Very cumbersome.

### Debug info

```shell
- [NA] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [NA] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [NA] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

Not a bug report
```

**Comment by Twixes** [comment] 2024-07-16 11:09
Hi! @suavesav, this is a great suggestion. It looks like a duplicate of #7288, so I'll close this, but do keep an eye on that pre-existing issue.

**Closed by Twixes** 2024-07-16 11:09 UTC
Labels: enhancement, team/product-analytics
