### ISSUE TITLE
Allow spend limits on Cloud

### ISSUE THREAD

**Issue by simfish85** [PostHog/posthog#9256] opened 2022-03-25 15:15 UTC
## Is your feature request related to a problem?

Some organizations want to control costs by setting an upper limit on the amount of events which are ingested beyond the 1m free tier on cloud.

## Describe the solution you'd like

Owners should be able to set either a monthly spend limit or event ingestion limit, and then either 

1. Event ingestion will be suspended for their account until the monthly count resets (or manually overridden by an account owner)
2. Ingestion carries on however events don't appear in insights/other front-end views

**Comment by timgl** [comment] 2022-03-29 11:50
Duplicate of #7083

**Closed by timgl** 2022-03-29 11:50 UTC
Labels: enhancement
