### ISSUE TITLE
Filtering by event property results in incorrect sessions

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2735] opened 2020-12-10 19:04 UTC
## Bug description

You can filter by user and event properties in sessions view. When filtering by event properties, this results in incomplete sessions being shown which contain only some of the events.

## Expected behavior

Show full sessions.

## How to reproduce

1. Go to sessions, find a user. Note session duration
2. Add 2 filters: one for that email, one for a specific event property (e.g. Library = posthog-python)
3. See only a few events

![Screenshot from 2020-12-10 21-03-07](https://user-images.githubusercontent.com/148820/101817520-27a9bd00-3b2b-11eb-9f89-80ed583be34d.png)

![Screenshot from 2020-12-10 21-03-16](https://user-images.githubusercontent.com/148820/101817511-24aecc80-3b2b-11eb-86de-1b09b677baae.png)

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

## Additional context

I think event property filters should not exist on sessions view in the current form but instead be paired up with actions/events as in insights.

Related issue https://github.com/PostHog/posthog/issues/2595

cc @paolodamico

**Comment by paolodamico** [comment] 2020-12-10 19:18
If I'm understanding this correctly, the problem is with the duration? Because I could easily conceive that from the first session list to the second the drop might be due to only that session having sent an event from the python library.

**Comment by macobo** [comment] 2020-12-10 19:21
No. The problem is that the session is incorrect - it _only_ lists events from posthog-python now even though there were many other events from posthog-js.

That is - in a sessions view even after filtering you'd expect to see a full session. At the moment you only get events that match filter.

**Comment by paolodamico** [comment] 2020-12-10 23:12
Right, that makes sense. Will this gets fixed with the filter refactor you worked with Eric? If not I'm thinking we're better off removing the filter altogether for now.

**Comment by macobo** [comment] 2020-12-11 14:14
Not fixed by that no. 

Let's discuss the filtering experience when we have a chance - I think having a way to filter by _user_ properties is legit needed on this page and that works as intended.

**Comment by paolodamico** [comment] 2020-12-14 19:01
I completely agree, even filtering by events is quite needed. I was thinking that for now we could remove filtering by event properties (while keeping filtering by user properties), until we can fix this. Thoughts?

**Comment by macobo** [comment] 2020-12-15 08:52
Yeah, let's do that while I'm adding the additional filtering capabilities.

**Closed** 2021-02-11 09:45 UTC
Labels: bug, sessions
