### ISSUE TITLE
Bar chart cohort not loading users

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#4532] opened 2021-05-27 20:26 UTC
## Bug description

This [chart](https://app.posthog.com/insights?insight=TRENDS&interval=day&actions=%5B%7B%22id%22%3A2671%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22%40doppler%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22person%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&properties=%5B%5D&filter_test_accounts=false&new_entity=%5B%5D&date_from=all&compare=false&display=ActionsBarValue) shows two users that fit the critieria.

If you click into the bar to look at the users, the modal loads and shows 0 users.

## Expected behavior

I'd expect to see the two users that were returned in the query.

## How to reproduce

1. Go to [chart](https://app.posthog.com/insights?insight=TRENDS&interval=day&actions=%5B%7B%22id%22%3A2671%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22%40doppler%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22person%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&properties=%5B%5D&filter_test_accounts=false&new_entity=%5B%5D&date_from=all&compare=false&display=ActionsBarValue) – observe two users.
2. Click into bar. No users load.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by kpthatsme** [comment] 2021-05-27 22:17
Update: Looks like it has something to do with filters. 

If you query the same chart sans email filter, users show up.

**Comment by alexkim205** [comment] 2021-06-02 19:44
### See below comment for the real root cause

### Investigation for my understanding

~~This mismatch stems from an incorrect `aggregated_value` that is being returned from the `/api/insight/trend/?insight=TRENDS` endpoint.~~

~~The `aggregated_value` is a deduplicated subsection of `count`. Count represents the total sum of users over a time range, whereas `aggregated value` represents the total **unique** users in that time range.~~

```
{
   "result":[
      {
         "action":{
           ...
         },
         "label":"User Signed Up",
         "count":0,
         "data":[],
         "labels":[],
         "days":[],
         "aggregated_value":2                 // should always be <= count
      }
   ],
   "next":null
}
```

~~We run into this issue whenever a user requests a trends graph with `math="dau"`. Doing so triggers a code path where we build up a SQL cmd with the aggregation operation - `count(DISTINCT person_id)` [[code]](https://github.com/alexkim205/posthog/blob/master/ee/clickhouse/queries/trends/util.py#L31-L32). Clickhouse chews on this SQL and spits back a result which we parse with a [callback](https://github.com/alexkim205/posthog/blob/master/ee/clickhouse/queries/trends/total_volume.py#L65-L66) that assigns this parameter:~~

```
{
   ...,
   "aggregated_value": result[0][0] if result and len(result) else 0,
   ...
}
```

**Comment by alexkim205** [comment] 2021-06-09 22:04
My brain hasn't been working since this morning so please excuse the mind dump below 😬

## Root Cause

Dug into this more and the root cause became a lot clearer when I got my hands on the SQL. 

The timestamp ranges specified in the [SQL for bar trends](https://github.com/PostHog/posthog/blob/f6d24270d36e15ab8c0d71b6d8c2e7f4eb7b8890/ee/clickhouse/sql/trends/volume.py#L5-L5), and the [one for the users list modal](https://github.com/PostHog/posthog/blob/f6d24270d36e15ab8c0d71b6d8c2e7f4eb7b8890/ee/clickhouse/sql/person.py#L242-L242) are different. For a sparse dataset like DAU trends with a specific filter, the former fetches for a larger time range while the latter fetches data within the timeframe flanking the earliest and latest data points. 

## Why? Deep Dive

I spent some time in the backend looking for a bug, but eventually discovered it in the frontend layer. 

The reason why the two SQL commands are different is because `date_from` and `date_to` are calculated from the earliest and latest timestamps in the bar graph's dataset. For a sparse dataset such as [DAU](https://app.posthog.com/insights?insight=TRENDS&interval=day&actions=%5B%7B%22id%22%3A2671%2C%22name%22%3A%22User%20Signed%20Up%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22%40doppler%22%2C%22operator%22%3A%22icontains%22%2C%22type%22%3A%22person%22%7D%5D%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%5D&properties=%5B%5D&filter_test_accounts=false&new_entity=%5B%5D&date_from=all&compare=false&display=ActionsBarValue), the deduped date ranges do not capture the entire time range of data points we observed. For example if there are 3 user signups that happened on 1/1/2020, 1/1/2021, 1/5/2021, and the first and last event were triggered by the same user, today's bar graph code would generate an SQL query for timerange 1/1/2020 - 1/5/2021, which will capture all 2 users. However when we click the bar graph to view those users, a new SQL would be created for timerange 1/1/2021 - 1/5/2021 since it only captures the min-max timestamps of the deduped users.

## Solution

The solution isn't as complicated as the bug. This can be fixed by generating the request from the filter parameters instead of the bar graph's data points [[code]](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/trends/viz/ActionsBarValueGraph.tsx#L81-L82)

**Closed** 2021-06-10 10:35 UTC
Labels: bug, core-experience
