### ISSUE TITLE
Export as CSV

### ISSUE THREAD

**Issue by eikooc** [PostHog/posthog#922] opened 2020-06-04 08:47 UTC
**Is your feature request related to a problem? Please describe.**
Teams in the organization want data to do further slicing and dicing, but it is currently inside a database of posthog.

**Describe the solution you'd like**
Be able to do data pulls such as export all events in the past 30 days as a CSV file.

**Describe alternatives you've considered**
Writing a custom SQL command to pull the data from the PostgreSQL database in the posthog Docker container.

**Additional context**
It is vital to be able to further process data with custom commands that doesn't necessarily fit into the dashboard of posthog, or for constructing ML models and so on.

**Comment by DannyBen** [comment] 2020-06-15 18:44
This at least partially overlaps with #724 - am also interested in this.
Saw there is an Export button in the people tab, would love to see more of that, and especially at the raw data level (events as I understand).

**Comment by timgl** [comment] 2020-06-15 18:47
Yep that's a duplicate of #724, thanks!

**Closed by timgl** 2020-06-15 18:47 UTC
Labels: enhancement
