### ISSUE TITLE
Alerts when conversion rate drops below a certain threshold

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18008] opened 2023-10-16 15:26 UTC
## Is your feature request related to a problem?

I want to get notified when a conversion rate of a funnel drops below a certain threshold.

## Additional context

https://posthog.com/questions/how-to-monitor-conversion-rates-and-set-up-alert-in-slack

**Comment by jannesblobel** [comment] 2024-06-24 12:01
+1

**Comment by ipropper** [comment] 2024-06-26 18:13
+1

**Comment by webjunkie** [comment] 2024-07-02 08:41
Closing as duplicate of #14331

**Closed by webjunkie** 2024-07-02 08:41 UTC
Labels: enhancement, feature/funnels, team/product-analytics
