### ISSUE TITLE
Filtering stopped working in session recording section 

### ISSUE THREAD

**Issue by kiranP007** [PostHog/posthog#23656] opened 2024-07-11 19:55 UTC
### Bug Description

Filtering using property has stopped working in session recording secction.

In my application, we add one property as identifier, at the time of initializing posthog, posthog initialization code as follows:
```
posthogJS.init(config.posthogApiKey, {
	api_host: config.posthogApiHost,
	loaded: function (posthog) {
	   posthog.identify(identifier, {
	      identifier,
	      clientId: clientId?.toLowerCase(),
	  });
	},
});
```  
			
Every recording has identifier, but when we try to filter recording using identifier or clientId, it is not filtering at all, it is showing all recordings. refer attachment for more info:
![filter broken](https://github.com/PostHog/posthog/assets/45927625/392b1dfb-c025-480c-9dc0-5ef138335b99)

posthog-js version:  1.128.1

**Comment by pauldambra** [comment] 2024-07-14 11:07
duplicate of #23697

**Closed by pauldambra** 2024-07-14 11:07 UTC
Labels: bug
