### ISSUE TITLE
Allow groups search

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8620] opened 2022-02-15 23:34 UTC
## Is your feature request related to a problem?

Wanted to find users from a particular organization (a group type we use internally), and was surprised that I couldn't search the groups.

## Describe the solution you'd like

A search bar in here:

<img width="617" alt="Screenshot 2022-02-15 at 23 34 00" src="https://user-images.githubusercontent.com/47497682/154167852-ab8f85fe-36c3-41c7-bd97-f6447df7a2c4.png">

Similar to the persons one:

<img width="1178" alt="Screenshot 2022-02-15 at 23 34 23" src="https://user-images.githubusercontent.com/47497682/154167885-527ec090-6d53-4ffc-a049-28c9f3717826.png">

## Describe alternatives you've considered

I can search the user profiles instead.

## Additional context

This isn't a blocker, but it's just a slight disappointment I had.

**Comment by macobo** [comment] 2022-02-16 08:14
Duplicate of https://github.com/PostHog/posthog/issues/7941

Thing is, the search in persons doesn't really work well. I would solve this as part of https://github.com/PostHog/posthog/issues/7963 and prioritize this highly.

**Closed by macobo** 2022-02-16 08:14 UTC
Labels: enhancement, group-analytics
