### ISSUE TITLE
Clicking points on graph doesn't return full list of users

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2284] opened 2020-11-09 14:10 UTC
## Bug description

Using app.posthog.com on the session recording dashboard...

Clicking here I'd expect a list of 15 users.
![Screenshot 2020-11-09 at 14 07 06](https://user-images.githubusercontent.com/47497682/98551306-11db7a80-2295-11eb-87e2-76fc50dd58c0.png)

The list is zero though (clicking other points sometimes shows a couple of users)
![Screenshot 2020-11-09 at 14 07 10](https://user-images.githubusercontent.com/47497682/98551342-1c960f80-2295-11eb-88ac-f02055aa3ab1.png)

## Expected behavior

If the point has 15 users as the data point I'd expect to see a list of 15 users.

**Comment by yakkomajuri** [comment] 2020-11-10 09:57
I believe this should be fixed + I can't reproduce it. Can you double-check now @jamesefhawkins ?

**Comment by EDsCODE** [comment] 2020-11-12 16:25
should be fixed by #2317, #2328, #2338. reopen if still broken!

**Closed by EDsCODE** 2020-11-12 16:25 UTC
Labels: bug
