### ISSUE TITLE
Error compleating the query with a simple average query

### ISSUE THREAD

**Issue by toger5** [PostHog/posthog#15839] opened 2023-06-01 10:49 UTC
## Bug description

*Please describe.*  
I want an average of a numeric field (percentageConcealedAudio) in a specific event (MediaReceived).
If i choose any time period longer than today I am getting the following error:
**There was an error completing this query**

*If this affects the front-end, screenshots would be of great help.*  

<img width="1489" alt="Screenshot 2023-06-01 at 12 41 01" src="https://github.com/PostHog/posthog/assets/16718859/30ed34e9-89bf-4885-82fa-49decad1d456">

The problem is solved, when adding a filter:
<img width="748" alt="Screenshot 2023-06-01 at 12 47 41" src="https://github.com/PostHog/posthog/assets/16718859/153bb1a4-f5c0-4af7-b4d9-d10c9d2592f1">
So this most likely has something to with non numeric values or undefined values (I cannot find such values in the data but there still might be events where this field is not numeric or undefined)

## How to reproduce
The error is only shown, when using sum and average. minimum and maximum values work.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
The percentage concealed audio events have up to 4 decimal digits.

**Comment by Twixes** [comment] 2023-06-01 11:50
Hi @toger5, can you share what version of PostHog you're using? Looking at your screenshots, it's at least a few months old and I believe this is not an issue in the latest version.

**Comment by toger5** [comment] 2023-06-02 12:38
Its version: 1.40.1

**Comment by Twixes** [comment] 2023-06-06 16:06
That version is 9 months old, so I will close this issue, given the problem is solved in newer versions.

**Closed by Twixes** 2023-06-06 16:06 UTC
Labels: bug

**Comment by toger5** [comment] 2023-06-13 09:48
We updated to version 1.43 now and I still need to filter with <2 to make it work. Otherwise posthog claims that it cannot find any data that fits to my query
