### ISSUE TITLE
> 10 days for Retention Matrix

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#5330] opened 2021-07-26 17:53 UTC
## Is your feature request related to a problem?

A [user requested](https://app.papercups.io/share?cid=a99709bc-dab5-44fd-b98a-8fa62e1ccea8&token=SFMyNTY.g2gDaAJtAAAAJDg3M2Y1MTAyLWQyNjctNGIwOS05ZGUwLWQ2ZTc0MWUwZTA3Nm0AAAAkNmRkNzNkMjAtZDcxYy00YTQ4LWFlODYtMjUxMzZkZmE4YTk5bgYASM3y43oBYgABUYA.n12t9stSp3jZg-GYzMbTS13Gct3rmci6Prm_4eUgb3s) for the ability to extend the retention matrix beyond 10 days, which is a legitimate use case for industries with longer trail times. 

## Describe the solution you'd like

<img width="1614" alt="Screen Shot 2021-07-26 at 10 51 15 AM" src="https://user-images.githubusercontent.com/13460330/127035437-e0906460-5d05-432b-893e-61919470d4d4.png">

## Describe alternatives you've considered

Specifying different end dates and piecing together 10 day windows.

**Comment by paolodamico** [comment] 2021-07-29 17:12
Duplicate of #2832

**Closed by paolodamico** 2021-07-29 17:12 UTC
Labels: core-analytics, core-experience, enhancement
